/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2AP-IEs"
 * 	found in "E2AP-IEs.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -fno-include-deps -findirect-choice -pdu=all -D e2ap`
 */

#ifndef	_ListedRecordsOnly_H_
#define	_ListedRecordsOnly_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ListedRecordsOnly {
	ListedRecordsOnly_true	= 0
	/*
	 * Enumeration is extensible
	 */
} e_ListedRecordsOnly;

/* ListedRecordsOnly */
typedef long	 ListedRecordsOnly_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ListedRecordsOnly_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ListedRecordsOnly;
extern const asn_INTEGER_specifics_t asn_SPC_ListedRecordsOnly_specs_1;
asn_struct_free_f ListedRecordsOnly_free;
asn_struct_print_f ListedRecordsOnly_print;
asn_constr_check_f ListedRecordsOnly_constraint;
ber_type_decoder_f ListedRecordsOnly_decode_ber;
der_type_encoder_f ListedRecordsOnly_encode_der;
xer_type_decoder_f ListedRecordsOnly_decode_xer;
xer_type_encoder_f ListedRecordsOnly_encode_xer;
jer_type_encoder_f ListedRecordsOnly_encode_jer;
oer_type_decoder_f ListedRecordsOnly_decode_oer;
oer_type_encoder_f ListedRecordsOnly_encode_oer;
per_type_decoder_f ListedRecordsOnly_decode_uper;
per_type_encoder_f ListedRecordsOnly_encode_uper;
per_type_decoder_f ListedRecordsOnly_decode_aper;
per_type_encoder_f ListedRecordsOnly_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ListedRecordsOnly_H_ */
#include "asn_internal.h"
