/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2AP-Containers"
 * 	found in "E2AP-Containers.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -fno-include-deps -findirect-choice -pdu=all -D e2ap`
 */

#include "ProtocolIE-SingleContainer.h"

/*
 * This type is implemented using RICaction_ToBeSetup_ItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using RICaction_Admitted_ItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using RICaction_NotAdmitted_ItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using RICsubscriptionAudit_ItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using RICsubscriptionAuditAction_ItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using RICsubscription_withCause_ItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using RICaction_ToBeRemovedForModification_ItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using RICaction_ToBeModifiedForModification_ItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using RICaction_ToBeAddedForModification_ItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using RICaction_RemovedForModification_ItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using RICaction_FailedToBeRemovedForModification_ItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using RICaction_ModifiedForModification_ItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using RICaction_FailedToBeModifiedForModification_ItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using RICaction_AddedForModification_ItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using RICaction_FailedToBeAddedForModification_ItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using RICaction_RequiredToBeModified_ItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using RICaction_RequiredToBeRemoved_ItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using RICaction_ConfirmedForModification_ItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using RICaction_RefusedToBeModified_ItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using RICaction_ConfirmedForRemoval_ItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using RICaction_RefusedToBeRemoved_ItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using RANfunctionStateControl_ItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using RICsubscriptionList_ItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using RICaction_ItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using RANfunctionStateConfirm_ItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using RANfunctionLoadRequest_ItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using RICsubscriptionLoadRequest_ItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using RICactionLoadRequest_ItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using RANfunctionLoadConfirm_ItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using RICsubscriptionLoadConfirm_ItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using RICactionLoadConfirm_ItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using RANfunctionLoad_ItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using RICsubscriptionLoad_ItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using RICactionLoad_ItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using E2connectionUpdate_ItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using E2connectionUpdateRemove_ItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using E2connectionSetupFailed_ItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using E2nodeComponentConfigAddition_ItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using E2nodeComponentConfigUpdate_ItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using E2nodeComponentConfigRemoval_ItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using E2nodeTNLassociationRemoval_ItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using E2nodeComponentConfigAdditionAck_ItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using E2nodeComponentConfigUpdateAck_ItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using E2nodeComponentConfigRemovalAck_ItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using RANfunction_ItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using RANfunctionID_ItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using RANfunctionIDcause_ItemIEs,
 * so here we adjust the DEF accordingly.
 */
static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_62P0_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_62P0 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_ProtocolIE_SingleContainer_62P0_tags_1,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_62P0_tags_1)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_62P0_tags_1[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_62P0_tags_1,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_62P0_tags_1)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_62P0_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_RICaction_ToBeSetup_ItemIEs_1,
	3,	/* Elements count */
	&asn_SPC_RICaction_ToBeSetup_ItemIEs_specs_1	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_62P1_tags_2[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_62P1 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_ProtocolIE_SingleContainer_62P1_tags_2,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_62P1_tags_2)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_62P1_tags_2[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_62P1_tags_2,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_62P1_tags_2)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_62P1_tags_2[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_RICaction_Admitted_ItemIEs_5,
	3,	/* Elements count */
	&asn_SPC_RICaction_Admitted_ItemIEs_specs_5	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_62P2_tags_3[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_62P2 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_ProtocolIE_SingleContainer_62P2_tags_3,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_62P2_tags_3)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_62P2_tags_3[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_62P2_tags_3,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_62P2_tags_3)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_62P2_tags_3[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_RICaction_NotAdmitted_ItemIEs_9,
	3,	/* Elements count */
	&asn_SPC_RICaction_NotAdmitted_ItemIEs_specs_9	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_62P3_tags_4[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_62P3 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_ProtocolIE_SingleContainer_62P3_tags_4,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_62P3_tags_4)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_62P3_tags_4[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_62P3_tags_4,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_62P3_tags_4)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_62P3_tags_4[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_RICsubscriptionAudit_ItemIEs_13,
	3,	/* Elements count */
	&asn_SPC_RICsubscriptionAudit_ItemIEs_specs_13	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_62P4_tags_5[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_62P4 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_ProtocolIE_SingleContainer_62P4_tags_5,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_62P4_tags_5)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_62P4_tags_5[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_62P4_tags_5,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_62P4_tags_5)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_62P4_tags_5[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_RICsubscriptionAuditAction_ItemIEs_17,
	3,	/* Elements count */
	&asn_SPC_RICsubscriptionAuditAction_ItemIEs_specs_17	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_62P5_tags_6[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_62P5 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_ProtocolIE_SingleContainer_62P5_tags_6,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_62P5_tags_6)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_62P5_tags_6[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_62P5_tags_6,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_62P5_tags_6)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_62P5_tags_6[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_RICsubscription_withCause_ItemIEs_21,
	3,	/* Elements count */
	&asn_SPC_RICsubscription_withCause_ItemIEs_specs_21	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_62P6_tags_7[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_62P6 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_ProtocolIE_SingleContainer_62P6_tags_7,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_62P6_tags_7)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_62P6_tags_7[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_62P6_tags_7,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_62P6_tags_7)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_62P6_tags_7[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_RICaction_ToBeRemovedForModification_ItemIEs_25,
	3,	/* Elements count */
	&asn_SPC_RICaction_ToBeRemovedForModification_ItemIEs_specs_25	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_62P7_tags_8[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_62P7 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_ProtocolIE_SingleContainer_62P7_tags_8,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_62P7_tags_8)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_62P7_tags_8[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_62P7_tags_8,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_62P7_tags_8)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_62P7_tags_8[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_RICaction_ToBeModifiedForModification_ItemIEs_29,
	3,	/* Elements count */
	&asn_SPC_RICaction_ToBeModifiedForModification_ItemIEs_specs_29	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_62P8_tags_9[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_62P8 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_ProtocolIE_SingleContainer_62P8_tags_9,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_62P8_tags_9)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_62P8_tags_9[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_62P8_tags_9,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_62P8_tags_9)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_62P8_tags_9[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_RICaction_ToBeAddedForModification_ItemIEs_33,
	3,	/* Elements count */
	&asn_SPC_RICaction_ToBeAddedForModification_ItemIEs_specs_33	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_62P9_tags_10[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_62P9 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_ProtocolIE_SingleContainer_62P9_tags_10,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_62P9_tags_10)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_62P9_tags_10[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_62P9_tags_10,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_62P9_tags_10)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_62P9_tags_10[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_RICaction_RemovedForModification_ItemIEs_37,
	3,	/* Elements count */
	&asn_SPC_RICaction_RemovedForModification_ItemIEs_specs_37	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_62P10_tags_11[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_62P10 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_ProtocolIE_SingleContainer_62P10_tags_11,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_62P10_tags_11)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_62P10_tags_11[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_62P10_tags_11,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_62P10_tags_11)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_62P10_tags_11[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_RICaction_FailedToBeRemovedForModification_ItemIEs_41,
	3,	/* Elements count */
	&asn_SPC_RICaction_FailedToBeRemovedForModification_ItemIEs_specs_41	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_62P11_tags_12[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_62P11 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_ProtocolIE_SingleContainer_62P11_tags_12,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_62P11_tags_12)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_62P11_tags_12[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_62P11_tags_12,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_62P11_tags_12)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_62P11_tags_12[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_RICaction_ModifiedForModification_ItemIEs_45,
	3,	/* Elements count */
	&asn_SPC_RICaction_ModifiedForModification_ItemIEs_specs_45	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_62P12_tags_13[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_62P12 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_ProtocolIE_SingleContainer_62P12_tags_13,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_62P12_tags_13)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_62P12_tags_13[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_62P12_tags_13,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_62P12_tags_13)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_62P12_tags_13[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_RICaction_FailedToBeModifiedForModification_ItemIEs_49,
	3,	/* Elements count */
	&asn_SPC_RICaction_FailedToBeModifiedForModification_ItemIEs_specs_49	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_62P13_tags_14[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_62P13 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_ProtocolIE_SingleContainer_62P13_tags_14,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_62P13_tags_14)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_62P13_tags_14[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_62P13_tags_14,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_62P13_tags_14)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_62P13_tags_14[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_RICaction_AddedForModification_ItemIEs_53,
	3,	/* Elements count */
	&asn_SPC_RICaction_AddedForModification_ItemIEs_specs_53	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_62P14_tags_15[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_62P14 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_ProtocolIE_SingleContainer_62P14_tags_15,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_62P14_tags_15)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_62P14_tags_15[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_62P14_tags_15,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_62P14_tags_15)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_62P14_tags_15[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_RICaction_FailedToBeAddedForModification_ItemIEs_57,
	3,	/* Elements count */
	&asn_SPC_RICaction_FailedToBeAddedForModification_ItemIEs_specs_57	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_62P15_tags_16[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_62P15 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_ProtocolIE_SingleContainer_62P15_tags_16,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_62P15_tags_16)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_62P15_tags_16[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_62P15_tags_16,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_62P15_tags_16)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_62P15_tags_16[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_RICaction_RequiredToBeModified_ItemIEs_61,
	3,	/* Elements count */
	&asn_SPC_RICaction_RequiredToBeModified_ItemIEs_specs_61	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_62P16_tags_17[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_62P16 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_ProtocolIE_SingleContainer_62P16_tags_17,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_62P16_tags_17)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_62P16_tags_17[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_62P16_tags_17,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_62P16_tags_17)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_62P16_tags_17[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_RICaction_RequiredToBeRemoved_ItemIEs_65,
	3,	/* Elements count */
	&asn_SPC_RICaction_RequiredToBeRemoved_ItemIEs_specs_65	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_62P17_tags_18[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_62P17 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_ProtocolIE_SingleContainer_62P17_tags_18,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_62P17_tags_18)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_62P17_tags_18[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_62P17_tags_18,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_62P17_tags_18)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_62P17_tags_18[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_RICaction_ConfirmedForModification_ItemIEs_69,
	3,	/* Elements count */
	&asn_SPC_RICaction_ConfirmedForModification_ItemIEs_specs_69	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_62P18_tags_19[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_62P18 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_ProtocolIE_SingleContainer_62P18_tags_19,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_62P18_tags_19)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_62P18_tags_19[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_62P18_tags_19,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_62P18_tags_19)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_62P18_tags_19[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_RICaction_RefusedToBeModified_ItemIEs_73,
	3,	/* Elements count */
	&asn_SPC_RICaction_RefusedToBeModified_ItemIEs_specs_73	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_62P19_tags_20[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_62P19 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_ProtocolIE_SingleContainer_62P19_tags_20,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_62P19_tags_20)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_62P19_tags_20[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_62P19_tags_20,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_62P19_tags_20)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_62P19_tags_20[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_RICaction_ConfirmedForRemoval_ItemIEs_77,
	3,	/* Elements count */
	&asn_SPC_RICaction_ConfirmedForRemoval_ItemIEs_specs_77	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_62P20_tags_21[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_62P20 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_ProtocolIE_SingleContainer_62P20_tags_21,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_62P20_tags_21)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_62P20_tags_21[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_62P20_tags_21,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_62P20_tags_21)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_62P20_tags_21[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_RICaction_RefusedToBeRemoved_ItemIEs_81,
	3,	/* Elements count */
	&asn_SPC_RICaction_RefusedToBeRemoved_ItemIEs_specs_81	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_62P21_tags_22[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_62P21 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_ProtocolIE_SingleContainer_62P21_tags_22,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_62P21_tags_22)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_62P21_tags_22[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_62P21_tags_22,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_62P21_tags_22)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_62P21_tags_22[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_RANfunctionStateControl_ItemIEs_85,
	3,	/* Elements count */
	&asn_SPC_RANfunctionStateControl_ItemIEs_specs_85	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_62P22_tags_23[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_62P22 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_ProtocolIE_SingleContainer_62P22_tags_23,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_62P22_tags_23)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_62P22_tags_23[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_62P22_tags_23,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_62P22_tags_23)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_62P22_tags_23[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_RICsubscriptionList_ItemIEs_89,
	3,	/* Elements count */
	&asn_SPC_RICsubscriptionList_ItemIEs_specs_89	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_62P23_tags_24[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_62P23 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_ProtocolIE_SingleContainer_62P23_tags_24,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_62P23_tags_24)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_62P23_tags_24[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_62P23_tags_24,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_62P23_tags_24)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_62P23_tags_24[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_RICaction_ItemIEs_93,
	3,	/* Elements count */
	&asn_SPC_RICaction_ItemIEs_specs_93	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_62P24_tags_25[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_62P24 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_ProtocolIE_SingleContainer_62P24_tags_25,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_62P24_tags_25)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_62P24_tags_25[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_62P24_tags_25,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_62P24_tags_25)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_62P24_tags_25[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_RANfunctionStateConfirm_ItemIEs_97,
	3,	/* Elements count */
	&asn_SPC_RANfunctionStateConfirm_ItemIEs_specs_97	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_62P25_tags_26[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_62P25 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_ProtocolIE_SingleContainer_62P25_tags_26,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_62P25_tags_26)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_62P25_tags_26[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_62P25_tags_26,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_62P25_tags_26)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_62P25_tags_26[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_RANfunctionLoadRequest_ItemIEs_101,
	3,	/* Elements count */
	&asn_SPC_RANfunctionLoadRequest_ItemIEs_specs_101	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_62P26_tags_27[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_62P26 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_ProtocolIE_SingleContainer_62P26_tags_27,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_62P26_tags_27)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_62P26_tags_27[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_62P26_tags_27,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_62P26_tags_27)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_62P26_tags_27[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_RICsubscriptionLoadRequest_ItemIEs_105,
	3,	/* Elements count */
	&asn_SPC_RICsubscriptionLoadRequest_ItemIEs_specs_105	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_62P27_tags_28[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_62P27 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_ProtocolIE_SingleContainer_62P27_tags_28,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_62P27_tags_28)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_62P27_tags_28[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_62P27_tags_28,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_62P27_tags_28)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_62P27_tags_28[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_RICactionLoadRequest_ItemIEs_109,
	3,	/* Elements count */
	&asn_SPC_RICactionLoadRequest_ItemIEs_specs_109	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_62P28_tags_29[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_62P28 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_ProtocolIE_SingleContainer_62P28_tags_29,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_62P28_tags_29)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_62P28_tags_29[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_62P28_tags_29,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_62P28_tags_29)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_62P28_tags_29[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_RANfunctionLoadConfirm_ItemIEs_113,
	3,	/* Elements count */
	&asn_SPC_RANfunctionLoadConfirm_ItemIEs_specs_113	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_62P29_tags_30[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_62P29 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_ProtocolIE_SingleContainer_62P29_tags_30,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_62P29_tags_30)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_62P29_tags_30[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_62P29_tags_30,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_62P29_tags_30)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_62P29_tags_30[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_RICsubscriptionLoadConfirm_ItemIEs_117,
	3,	/* Elements count */
	&asn_SPC_RICsubscriptionLoadConfirm_ItemIEs_specs_117	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_62P30_tags_31[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_62P30 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_ProtocolIE_SingleContainer_62P30_tags_31,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_62P30_tags_31)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_62P30_tags_31[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_62P30_tags_31,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_62P30_tags_31)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_62P30_tags_31[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_RICactionLoadConfirm_ItemIEs_121,
	3,	/* Elements count */
	&asn_SPC_RICactionLoadConfirm_ItemIEs_specs_121	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_62P31_tags_32[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_62P31 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_ProtocolIE_SingleContainer_62P31_tags_32,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_62P31_tags_32)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_62P31_tags_32[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_62P31_tags_32,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_62P31_tags_32)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_62P31_tags_32[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_RANfunctionLoad_ItemIEs_125,
	3,	/* Elements count */
	&asn_SPC_RANfunctionLoad_ItemIEs_specs_125	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_62P32_tags_33[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_62P32 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_ProtocolIE_SingleContainer_62P32_tags_33,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_62P32_tags_33)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_62P32_tags_33[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_62P32_tags_33,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_62P32_tags_33)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_62P32_tags_33[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_RICsubscriptionLoad_ItemIEs_129,
	3,	/* Elements count */
	&asn_SPC_RICsubscriptionLoad_ItemIEs_specs_129	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_62P33_tags_34[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_62P33 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_ProtocolIE_SingleContainer_62P33_tags_34,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_62P33_tags_34)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_62P33_tags_34[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_62P33_tags_34,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_62P33_tags_34)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_62P33_tags_34[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_RICactionLoad_ItemIEs_133,
	3,	/* Elements count */
	&asn_SPC_RICactionLoad_ItemIEs_specs_133	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_62P34_tags_35[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_62P34 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_ProtocolIE_SingleContainer_62P34_tags_35,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_62P34_tags_35)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_62P34_tags_35[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_62P34_tags_35,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_62P34_tags_35)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_62P34_tags_35[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_E2connectionUpdate_ItemIEs_137,
	3,	/* Elements count */
	&asn_SPC_E2connectionUpdate_ItemIEs_specs_137	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_62P35_tags_36[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_62P35 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_ProtocolIE_SingleContainer_62P35_tags_36,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_62P35_tags_36)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_62P35_tags_36[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_62P35_tags_36,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_62P35_tags_36)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_62P35_tags_36[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_E2connectionUpdateRemove_ItemIEs_141,
	3,	/* Elements count */
	&asn_SPC_E2connectionUpdateRemove_ItemIEs_specs_141	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_62P36_tags_37[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_62P36 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_ProtocolIE_SingleContainer_62P36_tags_37,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_62P36_tags_37)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_62P36_tags_37[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_62P36_tags_37,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_62P36_tags_37)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_62P36_tags_37[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_E2connectionSetupFailed_ItemIEs_145,
	3,	/* Elements count */
	&asn_SPC_E2connectionSetupFailed_ItemIEs_specs_145	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_62P37_tags_38[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_62P37 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_ProtocolIE_SingleContainer_62P37_tags_38,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_62P37_tags_38)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_62P37_tags_38[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_62P37_tags_38,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_62P37_tags_38)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_62P37_tags_38[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_E2nodeComponentConfigAddition_ItemIEs_149,
	3,	/* Elements count */
	&asn_SPC_E2nodeComponentConfigAddition_ItemIEs_specs_149	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_62P38_tags_39[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_62P38 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_ProtocolIE_SingleContainer_62P38_tags_39,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_62P38_tags_39)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_62P38_tags_39[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_62P38_tags_39,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_62P38_tags_39)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_62P38_tags_39[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_E2nodeComponentConfigUpdate_ItemIEs_153,
	3,	/* Elements count */
	&asn_SPC_E2nodeComponentConfigUpdate_ItemIEs_specs_153	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_62P39_tags_40[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_62P39 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_ProtocolIE_SingleContainer_62P39_tags_40,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_62P39_tags_40)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_62P39_tags_40[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_62P39_tags_40,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_62P39_tags_40)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_62P39_tags_40[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_E2nodeComponentConfigRemoval_ItemIEs_157,
	3,	/* Elements count */
	&asn_SPC_E2nodeComponentConfigRemoval_ItemIEs_specs_157	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_62P40_tags_41[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_62P40 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_ProtocolIE_SingleContainer_62P40_tags_41,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_62P40_tags_41)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_62P40_tags_41[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_62P40_tags_41,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_62P40_tags_41)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_62P40_tags_41[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_E2nodeTNLassociationRemoval_ItemIEs_161,
	3,	/* Elements count */
	&asn_SPC_E2nodeTNLassociationRemoval_ItemIEs_specs_161	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_62P41_tags_42[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_62P41 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_ProtocolIE_SingleContainer_62P41_tags_42,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_62P41_tags_42)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_62P41_tags_42[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_62P41_tags_42,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_62P41_tags_42)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_62P41_tags_42[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_E2nodeComponentConfigAdditionAck_ItemIEs_165,
	3,	/* Elements count */
	&asn_SPC_E2nodeComponentConfigAdditionAck_ItemIEs_specs_165	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_62P42_tags_43[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_62P42 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_ProtocolIE_SingleContainer_62P42_tags_43,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_62P42_tags_43)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_62P42_tags_43[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_62P42_tags_43,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_62P42_tags_43)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_62P42_tags_43[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_E2nodeComponentConfigUpdateAck_ItemIEs_169,
	3,	/* Elements count */
	&asn_SPC_E2nodeComponentConfigUpdateAck_ItemIEs_specs_169	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_62P43_tags_44[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_62P43 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_ProtocolIE_SingleContainer_62P43_tags_44,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_62P43_tags_44)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_62P43_tags_44[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_62P43_tags_44,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_62P43_tags_44)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_62P43_tags_44[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_E2nodeComponentConfigRemovalAck_ItemIEs_173,
	3,	/* Elements count */
	&asn_SPC_E2nodeComponentConfigRemovalAck_ItemIEs_specs_173	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_62P44_tags_45[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_62P44 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_ProtocolIE_SingleContainer_62P44_tags_45,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_62P44_tags_45)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_62P44_tags_45[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_62P44_tags_45,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_62P44_tags_45)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_62P44_tags_45[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_RANfunction_ItemIEs_177,
	3,	/* Elements count */
	&asn_SPC_RANfunction_ItemIEs_specs_177	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_62P45_tags_46[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_62P45 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_ProtocolIE_SingleContainer_62P45_tags_46,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_62P45_tags_46)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_62P45_tags_46[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_62P45_tags_46,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_62P45_tags_46)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_62P45_tags_46[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_RANfunctionID_ItemIEs_181,
	3,	/* Elements count */
	&asn_SPC_RANfunctionID_ItemIEs_specs_181	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_62P46_tags_47[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_62P46 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_ProtocolIE_SingleContainer_62P46_tags_47,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_62P46_tags_47)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_62P46_tags_47[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_62P46_tags_47,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_62P46_tags_47)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_62P46_tags_47[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_RANfunctionIDcause_ItemIEs_185,
	3,	/* Elements count */
	&asn_SPC_RANfunctionIDcause_ItemIEs_specs_185	/* Additional specs */
};

