/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2AP-Containers"
 * 	found in "E2AP-Containers.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -fno-include-deps -findirect-choice -pdu=all -D e2ap`
 */

#ifndef	_ProtocolIE_Container_H_
#define	_ProtocolIE_Container_H_


#include "asn_application.h"

/* Including external dependencies */
#include "asn_SEQUENCE_OF.h"
#include "constr_SEQUENCE_OF.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct RICsubscriptionRequest_IEs;
struct RICsubscriptionResponse_IEs;
struct RICsubscriptionFailure_IEs;
struct RICsubscriptionAuditRequest_IEs;
struct RICsubscriptionAuditResponse_IEs;
struct RICsubscriptionAuditFailure_IEs;
struct RICsubscriptionDeleteRequest_IEs;
struct RICsubscriptionDeleteResponse_IEs;
struct RICsubscriptionDeleteFailure_IEs;
struct RICsubscriptionDeleteRequired_IEs;
struct RICsubscriptionModificationRequest_IEs;
struct RICsubscriptionModificationResponse_IEs;
struct RICsubscriptionModificationFailure_IEs;
struct RICsubscriptionModificationRequired_IEs;
struct RICsubscriptionModificationConfirm_IEs;
struct RICsubscriptionModificationRefuse_IEs;
struct RICsubscriptionStateControlRequest_IEs;
struct RICsubscriptionStateControlResponse_IEs;
struct RICsubscriptionStateControlFailure_IEs;
struct RICassistanceRequest_IEs;
struct RICassistanceResponse_IEs;
struct RICassistanceFailure_IEs;
struct RICassistanceIndication_IEs;
struct RICassistanceHalt_IEs;
struct RICindication_IEs;
struct RICcontrolRequest_IEs;
struct RICcontrolAcknowledge_IEs;
struct RICcontrolFailure_IEs;
struct RICqueryRequest_IEs;
struct RICqueryResponse_IEs;
struct RICqueryFailure_IEs;
struct RICserviceLoadStatusRequest_IEs;
struct RICserviceLoadStatusResponse_IEs;
struct RICserviceLoadStatusFailure_IEs;
struct RICserviceLoadUpdate_IEs;
struct ErrorIndication_IEs;
struct E2setupRequestIEs;
struct E2setupResponseIEs;
struct E2setupFailureIEs;
struct E2connectionUpdate_IEs;
struct E2connectionUpdateAck_IEs;
struct E2connectionUpdateFailure_IEs;
struct E2nodeConfigurationUpdate_IEs;
struct E2nodeConfigurationUpdateAcknowledge_IEs;
struct E2nodeConfigurationUpdateFailure_IEs;
struct ResetRequestIEs;
struct ResetResponseIEs;
struct RICserviceUpdate_IEs;
struct RICserviceUpdateAcknowledge_IEs;
struct RICserviceUpdateFailure_IEs;
struct RICserviceQuery_IEs;
struct E2RemovalRequestIEs;
struct E2RemovalResponseIEs;
struct E2RemovalFailureIEs;

/* ProtocolIE-Container */
typedef struct ProtocolIE_Container_60P0 {
	A_SEQUENCE_OF(struct RICsubscriptionRequest_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_60P0_t;
typedef struct ProtocolIE_Container_60P1 {
	A_SEQUENCE_OF(struct RICsubscriptionResponse_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_60P1_t;
typedef struct ProtocolIE_Container_60P2 {
	A_SEQUENCE_OF(struct RICsubscriptionFailure_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_60P2_t;
typedef struct ProtocolIE_Container_60P3 {
	A_SEQUENCE_OF(struct RICsubscriptionAuditRequest_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_60P3_t;
typedef struct ProtocolIE_Container_60P4 {
	A_SEQUENCE_OF(struct RICsubscriptionAuditResponse_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_60P4_t;
typedef struct ProtocolIE_Container_60P5 {
	A_SEQUENCE_OF(struct RICsubscriptionAuditFailure_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_60P5_t;
typedef struct ProtocolIE_Container_60P6 {
	A_SEQUENCE_OF(struct RICsubscriptionDeleteRequest_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_60P6_t;
typedef struct ProtocolIE_Container_60P7 {
	A_SEQUENCE_OF(struct RICsubscriptionDeleteResponse_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_60P7_t;
typedef struct ProtocolIE_Container_60P8 {
	A_SEQUENCE_OF(struct RICsubscriptionDeleteFailure_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_60P8_t;
typedef struct ProtocolIE_Container_60P9 {
	A_SEQUENCE_OF(struct RICsubscriptionDeleteRequired_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_60P9_t;
typedef struct ProtocolIE_Container_60P10 {
	A_SEQUENCE_OF(struct RICsubscriptionModificationRequest_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_60P10_t;
typedef struct ProtocolIE_Container_60P11 {
	A_SEQUENCE_OF(struct RICsubscriptionModificationResponse_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_60P11_t;
typedef struct ProtocolIE_Container_60P12 {
	A_SEQUENCE_OF(struct RICsubscriptionModificationFailure_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_60P12_t;
typedef struct ProtocolIE_Container_60P13 {
	A_SEQUENCE_OF(struct RICsubscriptionModificationRequired_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_60P13_t;
typedef struct ProtocolIE_Container_60P14 {
	A_SEQUENCE_OF(struct RICsubscriptionModificationConfirm_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_60P14_t;
typedef struct ProtocolIE_Container_60P15 {
	A_SEQUENCE_OF(struct RICsubscriptionModificationRefuse_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_60P15_t;
typedef struct ProtocolIE_Container_60P16 {
	A_SEQUENCE_OF(struct RICsubscriptionStateControlRequest_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_60P16_t;
typedef struct ProtocolIE_Container_60P17 {
	A_SEQUENCE_OF(struct RICsubscriptionStateControlResponse_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_60P17_t;
typedef struct ProtocolIE_Container_60P18 {
	A_SEQUENCE_OF(struct RICsubscriptionStateControlFailure_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_60P18_t;
typedef struct ProtocolIE_Container_60P19 {
	A_SEQUENCE_OF(struct RICassistanceRequest_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_60P19_t;
typedef struct ProtocolIE_Container_60P20 {
	A_SEQUENCE_OF(struct RICassistanceResponse_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_60P20_t;
typedef struct ProtocolIE_Container_60P21 {
	A_SEQUENCE_OF(struct RICassistanceFailure_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_60P21_t;
typedef struct ProtocolIE_Container_60P22 {
	A_SEQUENCE_OF(struct RICassistanceIndication_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_60P22_t;
typedef struct ProtocolIE_Container_60P23 {
	A_SEQUENCE_OF(struct RICassistanceHalt_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_60P23_t;
typedef struct ProtocolIE_Container_60P24 {
	A_SEQUENCE_OF(struct RICindication_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_60P24_t;
typedef struct ProtocolIE_Container_60P25 {
	A_SEQUENCE_OF(struct RICcontrolRequest_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_60P25_t;
typedef struct ProtocolIE_Container_60P26 {
	A_SEQUENCE_OF(struct RICcontrolAcknowledge_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_60P26_t;
typedef struct ProtocolIE_Container_60P27 {
	A_SEQUENCE_OF(struct RICcontrolFailure_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_60P27_t;
typedef struct ProtocolIE_Container_60P28 {
	A_SEQUENCE_OF(struct RICqueryRequest_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_60P28_t;
typedef struct ProtocolIE_Container_60P29 {
	A_SEQUENCE_OF(struct RICqueryResponse_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_60P29_t;
typedef struct ProtocolIE_Container_60P30 {
	A_SEQUENCE_OF(struct RICqueryFailure_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_60P30_t;
typedef struct ProtocolIE_Container_60P31 {
	A_SEQUENCE_OF(struct RICserviceLoadStatusRequest_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_60P31_t;
typedef struct ProtocolIE_Container_60P32 {
	A_SEQUENCE_OF(struct RICserviceLoadStatusResponse_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_60P32_t;
typedef struct ProtocolIE_Container_60P33 {
	A_SEQUENCE_OF(struct RICserviceLoadStatusFailure_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_60P33_t;
typedef struct ProtocolIE_Container_60P34 {
	A_SEQUENCE_OF(struct RICserviceLoadUpdate_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_60P34_t;
typedef struct ProtocolIE_Container_60P35 {
	A_SEQUENCE_OF(struct ErrorIndication_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_60P35_t;
typedef struct ProtocolIE_Container_60P36 {
	A_SEQUENCE_OF(struct E2setupRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_60P36_t;
typedef struct ProtocolIE_Container_60P37 {
	A_SEQUENCE_OF(struct E2setupResponseIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_60P37_t;
typedef struct ProtocolIE_Container_60P38 {
	A_SEQUENCE_OF(struct E2setupFailureIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_60P38_t;
typedef struct ProtocolIE_Container_60P39 {
	A_SEQUENCE_OF(struct E2connectionUpdate_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_60P39_t;
typedef struct ProtocolIE_Container_60P40 {
	A_SEQUENCE_OF(struct E2connectionUpdateAck_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_60P40_t;
typedef struct ProtocolIE_Container_60P41 {
	A_SEQUENCE_OF(struct E2connectionUpdateFailure_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_60P41_t;
typedef struct ProtocolIE_Container_60P42 {
	A_SEQUENCE_OF(struct E2nodeConfigurationUpdate_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_60P42_t;
typedef struct ProtocolIE_Container_60P43 {
	A_SEQUENCE_OF(struct E2nodeConfigurationUpdateAcknowledge_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_60P43_t;
typedef struct ProtocolIE_Container_60P44 {
	A_SEQUENCE_OF(struct E2nodeConfigurationUpdateFailure_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_60P44_t;
typedef struct ProtocolIE_Container_60P45 {
	A_SEQUENCE_OF(struct ResetRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_60P45_t;
typedef struct ProtocolIE_Container_60P46 {
	A_SEQUENCE_OF(struct ResetResponseIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_60P46_t;
typedef struct ProtocolIE_Container_60P47 {
	A_SEQUENCE_OF(struct RICserviceUpdate_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_60P47_t;
typedef struct ProtocolIE_Container_60P48 {
	A_SEQUENCE_OF(struct RICserviceUpdateAcknowledge_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_60P48_t;
typedef struct ProtocolIE_Container_60P49 {
	A_SEQUENCE_OF(struct RICserviceUpdateFailure_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_60P49_t;
typedef struct ProtocolIE_Container_60P50 {
	A_SEQUENCE_OF(struct RICserviceQuery_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_60P50_t;
typedef struct ProtocolIE_Container_60P51 {
	A_SEQUENCE_OF(struct E2RemovalRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_60P51_t;
typedef struct ProtocolIE_Container_60P52 {
	A_SEQUENCE_OF(struct E2RemovalResponseIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_60P52_t;
typedef struct ProtocolIE_Container_60P53 {
	A_SEQUENCE_OF(struct E2RemovalFailureIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_60P53_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_60P0;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_60P0_specs_1;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_60P0_1[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_60P0_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_60P1;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_60P1_specs_3;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_60P1_3[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_60P1_constr_3;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_60P2;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_60P2_specs_5;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_60P2_5[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_60P2_constr_5;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_60P3;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_60P3_specs_7;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_60P3_7[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_60P3_constr_7;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_60P4;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_60P4_specs_9;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_60P4_9[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_60P4_constr_9;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_60P5;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_60P5_specs_11;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_60P5_11[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_60P5_constr_11;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_60P6;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_60P6_specs_13;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_60P6_13[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_60P6_constr_13;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_60P7;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_60P7_specs_15;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_60P7_15[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_60P7_constr_15;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_60P8;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_60P8_specs_17;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_60P8_17[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_60P8_constr_17;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_60P9;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_60P9_specs_19;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_60P9_19[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_60P9_constr_19;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_60P10;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_60P10_specs_21;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_60P10_21[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_60P10_constr_21;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_60P11;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_60P11_specs_23;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_60P11_23[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_60P11_constr_23;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_60P12;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_60P12_specs_25;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_60P12_25[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_60P12_constr_25;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_60P13;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_60P13_specs_27;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_60P13_27[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_60P13_constr_27;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_60P14;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_60P14_specs_29;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_60P14_29[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_60P14_constr_29;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_60P15;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_60P15_specs_31;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_60P15_31[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_60P15_constr_31;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_60P16;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_60P16_specs_33;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_60P16_33[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_60P16_constr_33;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_60P17;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_60P17_specs_35;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_60P17_35[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_60P17_constr_35;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_60P18;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_60P18_specs_37;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_60P18_37[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_60P18_constr_37;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_60P19;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_60P19_specs_39;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_60P19_39[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_60P19_constr_39;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_60P20;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_60P20_specs_41;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_60P20_41[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_60P20_constr_41;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_60P21;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_60P21_specs_43;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_60P21_43[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_60P21_constr_43;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_60P22;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_60P22_specs_45;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_60P22_45[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_60P22_constr_45;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_60P23;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_60P23_specs_47;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_60P23_47[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_60P23_constr_47;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_60P24;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_60P24_specs_49;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_60P24_49[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_60P24_constr_49;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_60P25;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_60P25_specs_51;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_60P25_51[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_60P25_constr_51;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_60P26;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_60P26_specs_53;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_60P26_53[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_60P26_constr_53;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_60P27;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_60P27_specs_55;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_60P27_55[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_60P27_constr_55;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_60P28;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_60P28_specs_57;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_60P28_57[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_60P28_constr_57;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_60P29;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_60P29_specs_59;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_60P29_59[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_60P29_constr_59;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_60P30;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_60P30_specs_61;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_60P30_61[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_60P30_constr_61;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_60P31;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_60P31_specs_63;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_60P31_63[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_60P31_constr_63;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_60P32;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_60P32_specs_65;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_60P32_65[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_60P32_constr_65;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_60P33;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_60P33_specs_67;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_60P33_67[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_60P33_constr_67;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_60P34;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_60P34_specs_69;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_60P34_69[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_60P34_constr_69;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_60P35;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_60P35_specs_71;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_60P35_71[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_60P35_constr_71;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_60P36;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_60P36_specs_73;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_60P36_73[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_60P36_constr_73;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_60P37;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_60P37_specs_75;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_60P37_75[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_60P37_constr_75;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_60P38;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_60P38_specs_77;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_60P38_77[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_60P38_constr_77;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_60P39;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_60P39_specs_79;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_60P39_79[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_60P39_constr_79;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_60P40;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_60P40_specs_81;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_60P40_81[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_60P40_constr_81;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_60P41;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_60P41_specs_83;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_60P41_83[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_60P41_constr_83;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_60P42;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_60P42_specs_85;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_60P42_85[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_60P42_constr_85;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_60P43;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_60P43_specs_87;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_60P43_87[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_60P43_constr_87;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_60P44;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_60P44_specs_89;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_60P44_89[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_60P44_constr_89;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_60P45;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_60P45_specs_91;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_60P45_91[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_60P45_constr_91;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_60P46;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_60P46_specs_93;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_60P46_93[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_60P46_constr_93;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_60P47;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_60P47_specs_95;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_60P47_95[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_60P47_constr_95;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_60P48;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_60P48_specs_97;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_60P48_97[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_60P48_constr_97;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_60P49;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_60P49_specs_99;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_60P49_99[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_60P49_constr_99;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_60P50;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_60P50_specs_101;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_60P50_101[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_60P50_constr_101;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_60P51;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_60P51_specs_103;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_60P51_103[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_60P51_constr_103;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_60P52;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_60P52_specs_105;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_60P52_105[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_60P52_constr_105;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_60P53;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_60P53_specs_107;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_60P53_107[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_60P53_constr_107;

#ifdef __cplusplus
}
#endif

#endif	/* _ProtocolIE_Container_H_ */
#include "asn_internal.h"
