/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2AP-PDU-Contents"
 * 	found in "E2AP-PDU-Contents.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -fno-include-deps -findirect-choice -pdu=all -D e2ap`
 */

#ifndef	_RANfunctionStateControl_Item_H_
#define	_RANfunctionStateControl_Item_H_


#include "asn_application.h"

/* Including external dependencies */
#include "RANfunctionID.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct RICsubscriptionToBeSuspended_List;
struct RICsubscriptionToBeResumed_List;

/* RANfunctionStateControl-Item */
typedef struct RANfunctionStateControl_Item {
	RANfunctionID_t	 ranFunctionID;
	struct RICsubscriptionToBeSuspended_List	*ricSubscriptionToBeSuspended_list;	/* OPTIONAL */
	struct RICsubscriptionToBeResumed_List	*ricSubscriptionToBeResumed_list;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RANfunctionStateControl_Item_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RANfunctionStateControl_Item;
extern asn_SEQUENCE_specifics_t asn_SPC_RANfunctionStateControl_Item_specs_1;
extern asn_TYPE_member_t asn_MBR_RANfunctionStateControl_Item_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _RANfunctionStateControl_Item_H_ */
#include "asn_internal.h"
