/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2AP-PDU-Contents"
 * 	found in "E2AP-PDU-Contents.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -fno-include-deps -findirect-choice -pdu=all -D e2ap`
 */

#ifndef	_RANfunctionLoadRequest_Item_H_
#define	_RANfunctionLoadRequest_Item_H_


#include "asn_application.h"

/* Including external dependencies */
#include "RANfunctionID.h"
#include "RICloadRequest.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct RICserviceLoadRequest;
struct RICsubscriptionLoadRequest_List;

/* RANfunctionLoadRequest-Item */
typedef struct RANfunctionLoadRequest_Item {
	RANfunctionID_t	 ranFunctionID;
	RICloadRequest_t	*ranFunctionLoadRequest;	/* OPTIONAL */
	struct RICserviceLoadRequest	*ricServiceLoadRequest;	/* OPTIONAL */
	struct RICsubscriptionLoadRequest_List	*ricSubscriptionLoadRequest_list;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RANfunctionLoadRequest_Item_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RANfunctionLoadRequest_Item;
extern asn_SEQUENCE_specifics_t asn_SPC_RANfunctionLoadRequest_Item_specs_1;
extern asn_TYPE_member_t asn_MBR_RANfunctionLoadRequest_Item_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _RANfunctionLoadRequest_Item_H_ */
#include "asn_internal.h"
