/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2AP-PDU-Contents"
 * 	found in "E2AP-PDU-Contents.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -fno-include-deps -findirect-choice -pdu=all -D e2ap`
 */

#include "RANfunctionStateConfirm-Item.h"

#include "RICsubscriptionSuspended-List.h"
#include "RICsubscriptionResumed-List.h"
asn_TYPE_member_t asn_MBR_RANfunctionStateConfirm_Item_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RANfunctionStateConfirm_Item, ranFunctionID),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RANfunctionID,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"ranFunctionID"
		},
	{ ATF_POINTER, 2, offsetof(struct RANfunctionStateConfirm_Item, ricSubscriptionSuspended_list),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RICsubscriptionSuspended_List,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"ricSubscriptionSuspended-list"
		},
	{ ATF_POINTER, 1, offsetof(struct RANfunctionStateConfirm_Item, ricSubscriptionResumed_list),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RICsubscriptionResumed_List,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"ricSubscriptionResumed-list"
		},
};
static const int asn_MAP_RANfunctionStateConfirm_Item_oms_1[] = { 1, 2 };
static const ber_tlv_tag_t asn_DEF_RANfunctionStateConfirm_Item_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_RANfunctionStateConfirm_Item_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* ranFunctionID */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* ricSubscriptionSuspended-list */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* ricSubscriptionResumed-list */
};
asn_SEQUENCE_specifics_t asn_SPC_RANfunctionStateConfirm_Item_specs_1 = {
	sizeof(struct RANfunctionStateConfirm_Item),
	offsetof(struct RANfunctionStateConfirm_Item, _asn_ctx),
	asn_MAP_RANfunctionStateConfirm_Item_tag2el_1,
	3,	/* Count of tags in the map */
	asn_MAP_RANfunctionStateConfirm_Item_oms_1,	/* Optional members */
	2, 0,	/* Root/Additions */
	3,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_RANfunctionStateConfirm_Item = {
	"RANfunctionStateConfirm-Item",
	"RANfunctionStateConfirm-Item",
	&asn_OP_SEQUENCE,
	asn_DEF_RANfunctionStateConfirm_Item_tags_1,
	sizeof(asn_DEF_RANfunctionStateConfirm_Item_tags_1)
		/sizeof(asn_DEF_RANfunctionStateConfirm_Item_tags_1[0]), /* 1 */
	asn_DEF_RANfunctionStateConfirm_Item_tags_1,	/* Same as above */
	sizeof(asn_DEF_RANfunctionStateConfirm_Item_tags_1)
		/sizeof(asn_DEF_RANfunctionStateConfirm_Item_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_RANfunctionStateConfirm_Item_1,
	3,	/* Elements count */
	&asn_SPC_RANfunctionStateConfirm_Item_specs_1	/* Additional specs */
};

