/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2AP-PDU-Contents"
 * 	found in "E2AP-PDU-Contents.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -fno-include-deps -findirect-choice -pdu=all -D e2ap`
 */

#ifndef	_RANfunctionLoadConfirm_Item_H_
#define	_RANfunctionLoadConfirm_Item_H_


#include "asn_application.h"

/* Including external dependencies */
#include "RANfunctionID.h"
#include "RICloadConfirm.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct RICserviceLoadConfirm;
struct RICsubscriptionLoadConfirm_List;

/* RANfunctionLoadConfirm-Item */
typedef struct RANfunctionLoadConfirm_Item {
	RANfunctionID_t	 ranFunctionID;
	RICloadConfirm_t	*ranFunctionLoadConfirm;	/* OPTIONAL */
	struct RICserviceLoadConfirm	*ricServiceLoadConfirm;	/* OPTIONAL */
	struct RICsubscriptionLoadConfirm_List	*ricSubscriptionLoadConfirm_list;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RANfunctionLoadConfirm_Item_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RANfunctionLoadConfirm_Item;
extern asn_SEQUENCE_specifics_t asn_SPC_RANfunctionLoadConfirm_Item_specs_1;
extern asn_TYPE_member_t asn_MBR_RANfunctionLoadConfirm_Item_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _RANfunctionLoadConfirm_Item_H_ */
#include "asn_internal.h"
