/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2AP-PDU-Contents"
 * 	found in "E2AP-PDU-Contents.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -fno-include-deps -findirect-choice -pdu=all -D e2ap`
 */

#include "RANfunctionLoadRequest-Item.h"

#include "RICserviceLoadRequest.h"
#include "RICsubscriptionLoadRequest-List.h"
asn_TYPE_member_t asn_MBR_RANfunctionLoadRequest_Item_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RANfunctionLoadRequest_Item, ranFunctionID),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RANfunctionID,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"ranFunctionID"
		},
	{ ATF_POINTER, 3, offsetof(struct RANfunctionLoadRequest_Item, ranFunctionLoadRequest),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RICloadRequest,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"ranFunctionLoadRequest"
		},
	{ ATF_POINTER, 2, offsetof(struct RANfunctionLoadRequest_Item, ricServiceLoadRequest),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RICserviceLoadRequest,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"ricServiceLoadRequest"
		},
	{ ATF_POINTER, 1, offsetof(struct RANfunctionLoadRequest_Item, ricSubscriptionLoadRequest_list),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RICsubscriptionLoadRequest_List,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"ricSubscriptionLoadRequest-list"
		},
};
static const int asn_MAP_RANfunctionLoadRequest_Item_oms_1[] = { 1, 2, 3 };
static const ber_tlv_tag_t asn_DEF_RANfunctionLoadRequest_Item_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_RANfunctionLoadRequest_Item_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* ranFunctionID */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* ranFunctionLoadRequest */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* ricServiceLoadRequest */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* ricSubscriptionLoadRequest-list */
};
asn_SEQUENCE_specifics_t asn_SPC_RANfunctionLoadRequest_Item_specs_1 = {
	sizeof(struct RANfunctionLoadRequest_Item),
	offsetof(struct RANfunctionLoadRequest_Item, _asn_ctx),
	asn_MAP_RANfunctionLoadRequest_Item_tag2el_1,
	4,	/* Count of tags in the map */
	asn_MAP_RANfunctionLoadRequest_Item_oms_1,	/* Optional members */
	3, 0,	/* Root/Additions */
	4,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_RANfunctionLoadRequest_Item = {
	"RANfunctionLoadRequest-Item",
	"RANfunctionLoadRequest-Item",
	&asn_OP_SEQUENCE,
	asn_DEF_RANfunctionLoadRequest_Item_tags_1,
	sizeof(asn_DEF_RANfunctionLoadRequest_Item_tags_1)
		/sizeof(asn_DEF_RANfunctionLoadRequest_Item_tags_1[0]), /* 1 */
	asn_DEF_RANfunctionLoadRequest_Item_tags_1,	/* Same as above */
	sizeof(asn_DEF_RANfunctionLoadRequest_Item_tags_1)
		/sizeof(asn_DEF_RANfunctionLoadRequest_Item_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_RANfunctionLoadRequest_Item_1,
	4,	/* Elements count */
	&asn_SPC_RANfunctionLoadRequest_Item_specs_1	/* Additional specs */
};

