/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2AP-PDU-Contents"
 * 	found in "E2AP-PDU-Contents.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -fno-include-deps -findirect-choice -pdu=all -D e2ap`
 */

#ifndef	_RANfunctionStateConfirm_Item_H_
#define	_RANfunctionStateConfirm_Item_H_


#include "asn_application.h"

/* Including external dependencies */
#include "RANfunctionID.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct RICsubscriptionSuspended_List;
struct RICsubscriptionResumed_List;

/* RANfunctionStateConfirm-Item */
typedef struct RANfunctionStateConfirm_Item {
	RANfunctionID_t	 ranFunctionID;
	struct RICsubscriptionSuspended_List	*ricSubscriptionSuspended_list;	/* OPTIONAL */
	struct RICsubscriptionResumed_List	*ricSubscriptionResumed_list;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RANfunctionStateConfirm_Item_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RANfunctionStateConfirm_Item;
extern asn_SEQUENCE_specifics_t asn_SPC_RANfunctionStateConfirm_Item_specs_1;
extern asn_TYPE_member_t asn_MBR_RANfunctionStateConfirm_Item_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _RANfunctionStateConfirm_Item_H_ */
#include "asn_internal.h"
