/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2AP-IEs"
 * 	found in "E2AP-IEs.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -fno-include-deps -findirect-choice -pdu=all -D e2ap`
 */

#ifndef	_RICassistanceSN_H_
#define	_RICassistanceSN_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* RICassistanceSN */
typedef long	 RICassistanceSN_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_RICassistanceSN_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_RICassistanceSN;
asn_struct_free_f RICassistanceSN_free;
asn_struct_print_f RICassistanceSN_print;
asn_constr_check_f RICassistanceSN_constraint;
ber_type_decoder_f RICassistanceSN_decode_ber;
der_type_encoder_f RICassistanceSN_encode_der;
xer_type_decoder_f RICassistanceSN_decode_xer;
xer_type_encoder_f RICassistanceSN_encode_xer;
jer_type_encoder_f RICassistanceSN_encode_jer;
oer_type_decoder_f RICassistanceSN_decode_oer;
oer_type_encoder_f RICassistanceSN_encode_oer;
per_type_decoder_f RICassistanceSN_decode_uper;
per_type_encoder_f RICassistanceSN_encode_uper;
per_type_decoder_f RICassistanceSN_decode_aper;
per_type_encoder_f RICassistanceSN_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _RICassistanceSN_H_ */
#include "asn_internal.h"
