/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2AP-PDU-Contents"
 * 	found in "E2AP-PDU-Contents.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -fno-include-deps -findirect-choice -pdu=all -D e2ap`
 */

#include "RICactionLoadConfirm-Item.h"

asn_TYPE_member_t asn_MBR_RICactionLoadConfirm_Item_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RICactionLoadConfirm_Item, ricActionID),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RICactionID,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"ricActionID"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RICactionLoadConfirm_Item, ricActionLoadConfirm),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RICloadConfirm,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"ricActionLoadConfirm"
		},
};
static const ber_tlv_tag_t asn_DEF_RICactionLoadConfirm_Item_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_RICactionLoadConfirm_Item_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* ricActionID */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* ricActionLoadConfirm */
};
asn_SEQUENCE_specifics_t asn_SPC_RICactionLoadConfirm_Item_specs_1 = {
	sizeof(struct RICactionLoadConfirm_Item),
	offsetof(struct RICactionLoadConfirm_Item, _asn_ctx),
	asn_MAP_RICactionLoadConfirm_Item_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	2,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_RICactionLoadConfirm_Item = {
	"RICactionLoadConfirm-Item",
	"RICactionLoadConfirm-Item",
	&asn_OP_SEQUENCE,
	asn_DEF_RICactionLoadConfirm_Item_tags_1,
	sizeof(asn_DEF_RICactionLoadConfirm_Item_tags_1)
		/sizeof(asn_DEF_RICactionLoadConfirm_Item_tags_1[0]), /* 1 */
	asn_DEF_RICactionLoadConfirm_Item_tags_1,	/* Same as above */
	sizeof(asn_DEF_RICactionLoadConfirm_Item_tags_1)
		/sizeof(asn_DEF_RICactionLoadConfirm_Item_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_RICactionLoadConfirm_Item_1,
	2,	/* Elements count */
	&asn_SPC_RICactionLoadConfirm_Item_specs_1	/* Additional specs */
};

