/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2AP-IEs"
 * 	found in "E2AP-IEs.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -fno-include-deps -findirect-choice -pdu=all -D e2ap`
 */

#ifndef	_RICloadRequest_H_
#define	_RICloadRequest_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum RICloadRequest {
	RICloadRequest_true	= 0
	/*
	 * Enumeration is extensible
	 */
} e_RICloadRequest;

/* RICloadRequest */
typedef long	 RICloadRequest_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_RICloadRequest_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_RICloadRequest;
extern const asn_INTEGER_specifics_t asn_SPC_RICloadRequest_specs_1;
asn_struct_free_f RICloadRequest_free;
asn_struct_print_f RICloadRequest_print;
asn_constr_check_f RICloadRequest_constraint;
ber_type_decoder_f RICloadRequest_decode_ber;
der_type_encoder_f RICloadRequest_encode_der;
xer_type_decoder_f RICloadRequest_decode_xer;
xer_type_encoder_f RICloadRequest_encode_xer;
jer_type_encoder_f RICloadRequest_encode_jer;
oer_type_decoder_f RICloadRequest_decode_oer;
oer_type_encoder_f RICloadRequest_encode_oer;
per_type_decoder_f RICloadRequest_decode_uper;
per_type_encoder_f RICloadRequest_encode_uper;
per_type_decoder_f RICloadRequest_decode_aper;
per_type_encoder_f RICloadRequest_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _RICloadRequest_H_ */
#include "asn_internal.h"
