/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2AP-IEs"
 * 	found in "E2AP-IEs.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -fno-include-deps -findirect-choice -pdu=all -D e2ap`
 */

#ifndef	_RICloadInformation_H_
#define	_RICloadInformation_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"
#include "NativeInteger.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum RICloadInformation__loadStatus {
	RICloadInformation__loadStatus_overload	= 0,
	RICloadInformation__loadStatus_notoverload	= 1
	/*
	 * Enumeration is extensible
	 */
} e_RICloadInformation__loadStatus;

/* RICloadInformation */
typedef struct RICloadInformation {
	long	*loadStatus;	/* OPTIONAL */
	long	*loadEstimate;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RICloadInformation_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_loadStatus_2;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_RICloadInformation;
extern asn_SEQUENCE_specifics_t asn_SPC_RICloadInformation_specs_1;
extern asn_TYPE_member_t asn_MBR_RICloadInformation_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _RICloadInformation_H_ */
#include "asn_internal.h"
