/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2AP-IEs"
 * 	found in "E2AP-IEs.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -fno-include-deps -findirect-choice -pdu=all -D e2ap`
 */

#ifndef	_RICserviceLoadRequest_H_
#define	_RICserviceLoadRequest_H_


#include "asn_application.h"

/* Including external dependencies */
#include "RICloadRequest.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* RICserviceLoadRequest */
typedef struct RICserviceLoadRequest {
	RICloadRequest_t	*ricServiceReportLoadRequest;	/* OPTIONAL */
	RICloadRequest_t	*ricServiceInsertLoadRequest;	/* OPTIONAL */
	RICloadRequest_t	*ricServiceControlLoadRequest;	/* OPTIONAL */
	RICloadRequest_t	*ricServicePolicyLoadRequest;	/* OPTIONAL */
	RICloadRequest_t	*ricServiceQueryLoadRequest;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RICserviceLoadRequest_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RICserviceLoadRequest;
extern asn_SEQUENCE_specifics_t asn_SPC_RICserviceLoadRequest_specs_1;
extern asn_TYPE_member_t asn_MBR_RICserviceLoadRequest_1[5];

#ifdef __cplusplus
}
#endif

#endif	/* _RICserviceLoadRequest_H_ */
#include "asn_internal.h"
