/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2AP-PDU-Contents"
 * 	found in "E2AP-PDU-Contents.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -fno-include-deps -findirect-choice -pdu=all -D e2ap`
 */

#ifndef	_RICsubscriptionLoadRequest_ItemIE_H_
#define	_RICsubscriptionLoadRequest_ItemIE_H_


#include "asn_application.h"

/* Including external dependencies */
#include "RICrequestID.h"
#include "RICloadRequest.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct RICactionLoadRequest_List;

/* RICsubscriptionLoadRequest-ItemIE */
typedef struct RICsubscriptionLoadRequest_ItemIE {
	RICrequestID_t	 ricRequestID;
	RICloadRequest_t	*ricSubscriptionLoadRequest;	/* OPTIONAL */
	struct RICactionLoadRequest_List	*ricActionLoadRequest_list;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RICsubscriptionLoadRequest_ItemIE_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RICsubscriptionLoadRequest_ItemIE;
extern asn_SEQUENCE_specifics_t asn_SPC_RICsubscriptionLoadRequest_ItemIE_specs_1;
extern asn_TYPE_member_t asn_MBR_RICsubscriptionLoadRequest_ItemIE_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _RICsubscriptionLoadRequest_ItemIE_H_ */
#include "asn_internal.h"
