/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2AP-PDU-Contents"
 * 	found in "E2AP-PDU-Contents.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -fno-include-deps -findirect-choice -pdu=all -D e2ap`
 */

#ifndef	_RICsubscriptionAuditAction_Item_H_
#define	_RICsubscriptionAuditAction_Item_H_


#include "asn_application.h"

/* Including external dependencies */
#include "RICrequestID.h"
#include "RANfunctionID.h"
#include "RICaction-Admitted-List.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* RICsubscriptionAuditAction-Item */
typedef struct RICsubscriptionAuditAction_Item {
	RICrequestID_t	 ricRequestID;
	RANfunctionID_t	 ranFunctionID;
	RICaction_Admitted_List_t	 ricAction_Admitted_List;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RICsubscriptionAuditAction_Item_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RICsubscriptionAuditAction_Item;
extern asn_SEQUENCE_specifics_t asn_SPC_RICsubscriptionAuditAction_Item_specs_1;
extern asn_TYPE_member_t asn_MBR_RICsubscriptionAuditAction_Item_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _RICsubscriptionAuditAction_Item_H_ */
#include "asn_internal.h"
