/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2AP-PDU-Contents"
 * 	found in "E2AP-PDU-Contents.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -fno-include-deps -findirect-choice -pdu=all -D e2ap`
 */

#include "RICsubscriptionList-Item.h"

#include "RICaction-List.h"
asn_TYPE_member_t asn_MBR_RICsubscriptionList_Item_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RICsubscriptionList_Item, ricRequestID),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RICrequestID,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"ricRequestID"
		},
	{ ATF_POINTER, 1, offsetof(struct RICsubscriptionList_Item, ricAction_list),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RICaction_List,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"ricAction-list"
		},
};
static const int asn_MAP_RICsubscriptionList_Item_oms_1[] = { 1 };
static const ber_tlv_tag_t asn_DEF_RICsubscriptionList_Item_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_RICsubscriptionList_Item_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* ricRequestID */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* ricAction-list */
};
asn_SEQUENCE_specifics_t asn_SPC_RICsubscriptionList_Item_specs_1 = {
	sizeof(struct RICsubscriptionList_Item),
	offsetof(struct RICsubscriptionList_Item, _asn_ctx),
	asn_MAP_RICsubscriptionList_Item_tag2el_1,
	2,	/* Count of tags in the map */
	asn_MAP_RICsubscriptionList_Item_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	2,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_RICsubscriptionList_Item = {
	"RICsubscriptionList-Item",
	"RICsubscriptionList-Item",
	&asn_OP_SEQUENCE,
	asn_DEF_RICsubscriptionList_Item_tags_1,
	sizeof(asn_DEF_RICsubscriptionList_Item_tags_1)
		/sizeof(asn_DEF_RICsubscriptionList_Item_tags_1[0]), /* 1 */
	asn_DEF_RICsubscriptionList_Item_tags_1,	/* Same as above */
	sizeof(asn_DEF_RICsubscriptionList_Item_tags_1)
		/sizeof(asn_DEF_RICsubscriptionList_Item_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_RICsubscriptionList_Item_1,
	2,	/* Elements count */
	&asn_SPC_RICsubscriptionList_Item_specs_1	/* Additional specs */
};

