/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2AP-PDU-Contents"
 * 	found in "E2AP-PDU-Contents.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -fno-include-deps -findirect-choice -pdu=all -D e2ap`
 */

#include "RICsubscriptionLoadRequest-ItemIE.h"

#include "RICactionLoadRequest-List.h"
asn_TYPE_member_t asn_MBR_RICsubscriptionLoadRequest_ItemIE_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RICsubscriptionLoadRequest_ItemIE, ricRequestID),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RICrequestID,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"ricRequestID"
		},
	{ ATF_POINTER, 2, offsetof(struct RICsubscriptionLoadRequest_ItemIE, ricSubscriptionLoadRequest),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RICloadRequest,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"ricSubscriptionLoadRequest"
		},
	{ ATF_POINTER, 1, offsetof(struct RICsubscriptionLoadRequest_ItemIE, ricActionLoadRequest_list),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RICactionLoadRequest_List,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"ricActionLoadRequest-list"
		},
};
static const int asn_MAP_RICsubscriptionLoadRequest_ItemIE_oms_1[] = { 1, 2 };
static const ber_tlv_tag_t asn_DEF_RICsubscriptionLoadRequest_ItemIE_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_RICsubscriptionLoadRequest_ItemIE_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* ricRequestID */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* ricSubscriptionLoadRequest */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* ricActionLoadRequest-list */
};
asn_SEQUENCE_specifics_t asn_SPC_RICsubscriptionLoadRequest_ItemIE_specs_1 = {
	sizeof(struct RICsubscriptionLoadRequest_ItemIE),
	offsetof(struct RICsubscriptionLoadRequest_ItemIE, _asn_ctx),
	asn_MAP_RICsubscriptionLoadRequest_ItemIE_tag2el_1,
	3,	/* Count of tags in the map */
	asn_MAP_RICsubscriptionLoadRequest_ItemIE_oms_1,	/* Optional members */
	2, 0,	/* Root/Additions */
	3,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_RICsubscriptionLoadRequest_ItemIE = {
	"RICsubscriptionLoadRequest-ItemIE",
	"RICsubscriptionLoadRequest-ItemIE",
	&asn_OP_SEQUENCE,
	asn_DEF_RICsubscriptionLoadRequest_ItemIE_tags_1,
	sizeof(asn_DEF_RICsubscriptionLoadRequest_ItemIE_tags_1)
		/sizeof(asn_DEF_RICsubscriptionLoadRequest_ItemIE_tags_1[0]), /* 1 */
	asn_DEF_RICsubscriptionLoadRequest_ItemIE_tags_1,	/* Same as above */
	sizeof(asn_DEF_RICsubscriptionLoadRequest_ItemIE_tags_1)
		/sizeof(asn_DEF_RICsubscriptionLoadRequest_ItemIE_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_RICsubscriptionLoadRequest_ItemIE_1,
	3,	/* Elements count */
	&asn_SPC_RICsubscriptionLoadRequest_ItemIE_specs_1	/* Additional specs */
};

