/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2AP-IEs"
 * 	found in "E2AP-IEs.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -fno-include-deps -findirect-choice -pdu=all -D e2ap`
 */

#ifndef	_RICsubscriptionAuditFlag_H_
#define	_RICsubscriptionAuditFlag_H_


#include "asn_application.h"

/* Including external dependencies */
#include "ListedRecordsOnly.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* RICsubscriptionAuditFlag */
typedef struct RICsubscriptionAuditFlag {
	ListedRecordsOnly_t	*listedRecordsOnly;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RICsubscriptionAuditFlag_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RICsubscriptionAuditFlag;
extern asn_SEQUENCE_specifics_t asn_SPC_RICsubscriptionAuditFlag_specs_1;
extern asn_TYPE_member_t asn_MBR_RICsubscriptionAuditFlag_1[1];

#ifdef __cplusplus
}
#endif

#endif	/* _RICsubscriptionAuditFlag_H_ */
#include "asn_internal.h"
