/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2AP-PDU-Contents"
 * 	found in "E2AP-PDU-Contents.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -fno-include-deps -findirect-choice -pdu=all -D e2ap`
 */

#ifndef	_RICsubscriptionAuditActionList_H_
#define	_RICsubscriptionAuditActionList_H_


#include "asn_application.h"

/* Including external dependencies */
#include "asn_SEQUENCE_OF.h"
#include "constr_SEQUENCE_OF.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ProtocolIE_SingleContainer;

/* RICsubscriptionAuditActionList */
typedef struct RICsubscriptionAuditActionList {
	A_SEQUENCE_OF(struct ProtocolIE_SingleContainer) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RICsubscriptionAuditActionList_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RICsubscriptionAuditActionList;
extern asn_SET_OF_specifics_t asn_SPC_RICsubscriptionAuditActionList_specs_1;
extern asn_TYPE_member_t asn_MBR_RICsubscriptionAuditActionList_1[1];
extern asn_per_constraints_t asn_PER_type_RICsubscriptionAuditActionList_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _RICsubscriptionAuditActionList_H_ */
#include "asn_internal.h"
