/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2AP-IEs"
 * 	found in "E2AP-IEs.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -fno-include-deps -findirect-choice -pdu=all -D e2ap`
 */

#ifndef	_RICserviceLoadConfirm_H_
#define	_RICserviceLoadConfirm_H_


#include "asn_application.h"

/* Including external dependencies */
#include "RICloadConfirm.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* RICserviceLoadConfirm */
typedef struct RICserviceLoadConfirm {
	RICloadConfirm_t	*ricServiceReportLoadConfirm;	/* OPTIONAL */
	RICloadConfirm_t	*ricServiceInsertLoadConfirm;	/* OPTIONAL */
	RICloadConfirm_t	*ricServiceControlLoadConfirm;	/* OPTIONAL */
	RICloadConfirm_t	*ricServicePolicyLoadConfirm;	/* OPTIONAL */
	RICloadConfirm_t	*ricServiceQueryLoadConfirm;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RICserviceLoadConfirm_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RICserviceLoadConfirm;
extern asn_SEQUENCE_specifics_t asn_SPC_RICserviceLoadConfirm_specs_1;
extern asn_TYPE_member_t asn_MBR_RICserviceLoadConfirm_1[5];

#ifdef __cplusplus
}
#endif

#endif	/* _RICserviceLoadConfirm_H_ */
#include "asn_internal.h"
