/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2AP-IEs"
 * 	found in "E2AP-IEs.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -fno-include-deps -findirect-choice -pdu=all -D e2ap`
 */

#ifndef	_ServiceLayerCause_H_
#define	_ServiceLayerCause_H_


#include "asn_application.h"

/* Including external dependencies */
#include "OCTET_STRING.h"

#ifdef __cplusplus
extern "C" {
#endif

/* ServiceLayerCause */
typedef OCTET_STRING_t	 ServiceLayerCause_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ServiceLayerCause;
asn_struct_free_f ServiceLayerCause_free;
asn_struct_print_f ServiceLayerCause_print;
asn_constr_check_f ServiceLayerCause_constraint;
ber_type_decoder_f ServiceLayerCause_decode_ber;
der_type_encoder_f ServiceLayerCause_encode_der;
xer_type_decoder_f ServiceLayerCause_decode_xer;
xer_type_encoder_f ServiceLayerCause_encode_xer;
jer_type_encoder_f ServiceLayerCause_encode_jer;
oer_type_decoder_f ServiceLayerCause_decode_oer;
oer_type_encoder_f ServiceLayerCause_encode_oer;
per_type_decoder_f ServiceLayerCause_decode_uper;
per_type_encoder_f ServiceLayerCause_encode_uper;
per_type_decoder_f ServiceLayerCause_decode_aper;
per_type_encoder_f ServiceLayerCause_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ServiceLayerCause_H_ */
#include "asn_internal.h"
