/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-RC-IEs"
 * 	found in "E2SM-RC-v06.00.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -fno-include-deps -findirect-choice -pdu=all -D rc`
 */

#ifndef	_ServingCellConfigCommon_H_
#define	_ServingCellConfigCommon_H_


#include "asn_application.h"

/* Including external dependencies */
#include "OCTET_STRING.h"
#include "NativeEnumerated.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ServingCellConfigCommon__ssbPeriodicity {
	ServingCellConfigCommon__ssbPeriodicity_ms5	= 0,
	ServingCellConfigCommon__ssbPeriodicity_ms10	= 1,
	ServingCellConfigCommon__ssbPeriodicity_ms20	= 2,
	ServingCellConfigCommon__ssbPeriodicity_ms40	= 3,
	ServingCellConfigCommon__ssbPeriodicity_ms80	= 4,
	ServingCellConfigCommon__ssbPeriodicity_ms160	= 5
	/*
	 * Enumeration is extensible
	 */
} e_ServingCellConfigCommon__ssbPeriodicity;
typedef enum ServingCellConfigCommon__ssbSubcarrierSpacing {
	ServingCellConfigCommon__ssbSubcarrierSpacing_kHz15	= 0,
	ServingCellConfigCommon__ssbSubcarrierSpacing_kHz30	= 1,
	ServingCellConfigCommon__ssbSubcarrierSpacing_kHz60	= 2,
	ServingCellConfigCommon__ssbSubcarrierSpacing_kHz120	= 3,
	ServingCellConfigCommon__ssbSubcarrierSpacing_kHz240	= 4,
	ServingCellConfigCommon__ssbSubcarrierSpacing_kHz480_v1700	= 5,
	ServingCellConfigCommon__ssbSubcarrierSpacing_kHz960_v1700	= 6
	/*
	 * Enumeration is extensible
	 */
} e_ServingCellConfigCommon__ssbSubcarrierSpacing;

/* ServingCellConfigCommon */
typedef struct ServingCellConfigCommon {
	OCTET_STRING_t	 ssbPositionsInBurst;
	long	 ssbPeriodicity;
	long	 ssbSubcarrierSpacing;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ServingCellConfigCommon_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_ssbPeriodicity_3;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_ssbSubcarrierSpacing_11;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_ServingCellConfigCommon;
extern asn_SEQUENCE_specifics_t asn_SPC_ServingCellConfigCommon_specs_1;
extern asn_TYPE_member_t asn_MBR_ServingCellConfigCommon_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _ServingCellConfigCommon_H_ */
#include "asn_internal.h"
