/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-RC-IEs"
 * 	found in "E2SM-RC-v06.00.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -fno-include-deps -findirect-choice -pdu=all -D rc`
 */

#include "ServingCellConfigCommon.h"

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
#if !defined(ASN_DISABLE_OER_SUPPORT)
static asn_oer_constraints_t asn_OER_type_ssbPeriodicity_constr_3 CC_NOTUSED = {
	{ 0, 0 },
	-1};
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
static asn_per_constraints_t asn_PER_type_ssbPeriodicity_constr_3 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  3,  3,  0,  5 }	/* (0..5,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_OER_SUPPORT)
static asn_oer_constraints_t asn_OER_type_ssbSubcarrierSpacing_constr_11 CC_NOTUSED = {
	{ 0, 0 },
	-1};
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
static asn_per_constraints_t asn_PER_type_ssbSubcarrierSpacing_constr_11 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  3,  3,  0,  6 }	/* (0..6,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
static const asn_INTEGER_enum_map_t asn_MAP_ssbPeriodicity_value2enum_3[] = {
	{ 0,	3,	"ms5" },
	{ 1,	4,	"ms10" },
	{ 2,	4,	"ms20" },
	{ 3,	4,	"ms40" },
	{ 4,	4,	"ms80" },
	{ 5,	5,	"ms160" }
	/* This list is extensible */
};
static const unsigned int asn_MAP_ssbPeriodicity_enum2value_3[] = {
	1,	/* ms10(1) */
	5,	/* ms160(5) */
	2,	/* ms20(2) */
	3,	/* ms40(3) */
	0,	/* ms5(0) */
	4	/* ms80(4) */
	/* This list is extensible */
};
static const asn_INTEGER_specifics_t asn_SPC_ssbPeriodicity_specs_3 = {
	asn_MAP_ssbPeriodicity_value2enum_3,	/* "tag" => N; sorted by tag */
	asn_MAP_ssbPeriodicity_enum2value_3,	/* N => "tag"; sorted by N */
	6,	/* Number of elements in the maps */
	7,	/* Extensions before this member */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_ssbPeriodicity_tags_3[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ssbPeriodicity_3 = {
	"ssbPeriodicity",
	"ssbPeriodicity",
	&asn_OP_NativeEnumerated,
	asn_DEF_ssbPeriodicity_tags_3,
	sizeof(asn_DEF_ssbPeriodicity_tags_3)
		/sizeof(asn_DEF_ssbPeriodicity_tags_3[0]) - 1, /* 1 */
	asn_DEF_ssbPeriodicity_tags_3,	/* Same as above */
	sizeof(asn_DEF_ssbPeriodicity_tags_3)
		/sizeof(asn_DEF_ssbPeriodicity_tags_3[0]), /* 2 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		&asn_OER_type_ssbPeriodicity_constr_3,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_ssbPeriodicity_constr_3,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		NativeEnumerated_constraint
	},
	0, 0,	/* Defined elsewhere */
	&asn_SPC_ssbPeriodicity_specs_3	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_ssbSubcarrierSpacing_value2enum_11[] = {
	{ 0,	5,	"kHz15" },
	{ 1,	5,	"kHz30" },
	{ 2,	5,	"kHz60" },
	{ 3,	6,	"kHz120" },
	{ 4,	6,	"kHz240" },
	{ 5,	12,	"kHz480-v1700" },
	{ 6,	12,	"kHz960-v1700" }
	/* This list is extensible */
};
static const unsigned int asn_MAP_ssbSubcarrierSpacing_enum2value_11[] = {
	3,	/* kHz120(3) */
	0,	/* kHz15(0) */
	4,	/* kHz240(4) */
	1,	/* kHz30(1) */
	5,	/* kHz480-v1700(5) */
	2,	/* kHz60(2) */
	6	/* kHz960-v1700(6) */
	/* This list is extensible */
};
static const asn_INTEGER_specifics_t asn_SPC_ssbSubcarrierSpacing_specs_11 = {
	asn_MAP_ssbSubcarrierSpacing_value2enum_11,	/* "tag" => N; sorted by tag */
	asn_MAP_ssbSubcarrierSpacing_enum2value_11,	/* N => "tag"; sorted by N */
	7,	/* Number of elements in the maps */
	8,	/* Extensions before this member */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_ssbSubcarrierSpacing_tags_11[] = {
	(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ssbSubcarrierSpacing_11 = {
	"ssbSubcarrierSpacing",
	"ssbSubcarrierSpacing",
	&asn_OP_NativeEnumerated,
	asn_DEF_ssbSubcarrierSpacing_tags_11,
	sizeof(asn_DEF_ssbSubcarrierSpacing_tags_11)
		/sizeof(asn_DEF_ssbSubcarrierSpacing_tags_11[0]) - 1, /* 1 */
	asn_DEF_ssbSubcarrierSpacing_tags_11,	/* Same as above */
	sizeof(asn_DEF_ssbSubcarrierSpacing_tags_11)
		/sizeof(asn_DEF_ssbSubcarrierSpacing_tags_11[0]), /* 2 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		&asn_OER_type_ssbSubcarrierSpacing_constr_11,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_ssbSubcarrierSpacing_constr_11,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		NativeEnumerated_constraint
	},
	0, 0,	/* Defined elsewhere */
	&asn_SPC_ssbSubcarrierSpacing_specs_11	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ServingCellConfigCommon_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ServingCellConfigCommon, ssbPositionsInBurst),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"ssbPositionsInBurst"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ServingCellConfigCommon, ssbPeriodicity),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ssbPeriodicity_3,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"ssbPeriodicity"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ServingCellConfigCommon, ssbSubcarrierSpacing),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ssbSubcarrierSpacing_11,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"ssbSubcarrierSpacing"
		},
};
static const ber_tlv_tag_t asn_DEF_ServingCellConfigCommon_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ServingCellConfigCommon_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* ssbPositionsInBurst */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* ssbPeriodicity */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* ssbSubcarrierSpacing */
};
asn_SEQUENCE_specifics_t asn_SPC_ServingCellConfigCommon_specs_1 = {
	sizeof(struct ServingCellConfigCommon),
	offsetof(struct ServingCellConfigCommon, _asn_ctx),
	asn_MAP_ServingCellConfigCommon_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	3,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_ServingCellConfigCommon = {
	"ServingCellConfigCommon",
	"ServingCellConfigCommon",
	&asn_OP_SEQUENCE,
	asn_DEF_ServingCellConfigCommon_tags_1,
	sizeof(asn_DEF_ServingCellConfigCommon_tags_1)
		/sizeof(asn_DEF_ServingCellConfigCommon_tags_1[0]), /* 1 */
	asn_DEF_ServingCellConfigCommon_tags_1,	/* Same as above */
	sizeof(asn_DEF_ServingCellConfigCommon_tags_1)
		/sizeof(asn_DEF_ServingCellConfigCommon_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_ServingCellConfigCommon_1,
	3,	/* Elements count */
	&asn_SPC_ServingCellConfigCommon_specs_1	/* Additional specs */
};

