/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-RC-IEs"
 * 	found in "E2SM-RC-v06.00.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -fno-include-deps -findirect-choice -pdu=all -D ../../../lib/oran/e2sm/rc`
 */

#ifndef	_AdditionalSupportedFormat_H_
#define	_AdditionalSupportedFormat_H_


#include "asn_application.h"

/* Including external dependencies */
#include "RIC-Format-Type.h"
#include "RIC-ControlAction-ID.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* AdditionalSupportedFormat */
typedef struct AdditionalSupportedFormat {
	RIC_Format_Type_t	 ric_ControlHeaderFormat_Type;
	RIC_Format_Type_t	 ric_ControlMessageFormat_Type;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	RIC_Format_Type_t	*ric_ControlOutcomeFormat_Type;	/* OPTIONAL */
	RIC_ControlAction_ID_t	*ric_ControlAction_ID;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AdditionalSupportedFormat_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AdditionalSupportedFormat;
extern asn_SEQUENCE_specifics_t asn_SPC_AdditionalSupportedFormat_specs_1;
extern asn_TYPE_member_t asn_MBR_AdditionalSupportedFormat_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _AdditionalSupportedFormat_H_ */
#include "asn_internal.h"
