/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-RC-IEs"
 * 	found in "E2SM-RC-v06.00.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -fno-include-deps -findirect-choice -pdu=all -D ../../../lib/oran/e2sm/rc`
 */

#include "E2SM-RC-ControlMessage-Format5.h"

/*
 * This type is implemented using NULL,
 * so here we adjust the DEF accordingly.
 */
static const ber_tlv_tag_t asn_DEF_E2SM_RC_ControlMessage_Format5_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (5 << 2))
};
asn_TYPE_descriptor_t asn_DEF_E2SM_RC_ControlMessage_Format5 = {
	"E2SM-RC-ControlMessage-Format5",
	"E2SM-RC-ControlMessage-Format5",
	&asn_OP_NULL,
	asn_DEF_E2SM_RC_ControlMessage_Format5_tags_1,
	sizeof(asn_DEF_E2SM_RC_ControlMessage_Format5_tags_1)
		/sizeof(asn_DEF_E2SM_RC_ControlMessage_Format5_tags_1[0]), /* 1 */
	asn_DEF_E2SM_RC_ControlMessage_Format5_tags_1,	/* Same as above */
	sizeof(asn_DEF_E2SM_RC_ControlMessage_Format5_tags_1)
		/sizeof(asn_DEF_E2SM_RC_ControlMessage_Format5_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		NULL_constraint
	},
	0, 0,	/* No members */
	0	/* No specifics */
};

