/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-RC-IEs"
 * 	found in "E2SM-RC-v06.00.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -fno-include-deps -findirect-choice -pdu=all -D ../../../lib/oran/e2sm/rc`
 */

#ifndef	_NeighbourCell_Item_H_
#define	_NeighbourCell_Item_H_


#include "asn_application.h"

/* Including external dependencies */
#include "constr_CHOICE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NeighbourCell_Item_PR {
	NeighbourCell_Item_PR_NOTHING,	/* No components present */
	NeighbourCell_Item_PR_ranType_Choice_NR,
	NeighbourCell_Item_PR_ranType_Choice_EUTRA
	/* Extensions may appear below */
	
} NeighbourCell_Item_PR;

/* Forward declarations */
struct NeighbourCell_Item_Choice_NR;
struct NeighbourCell_Item_Choice_E_UTRA;

/* NeighbourCell-Item */
typedef struct NeighbourCell_Item {
	NeighbourCell_Item_PR present;
	union NeighbourCell_Item_u {
		struct NeighbourCell_Item_Choice_NR	*ranType_Choice_NR;
		struct NeighbourCell_Item_Choice_E_UTRA	*ranType_Choice_EUTRA;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NeighbourCell_Item_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NeighbourCell_Item;
extern asn_CHOICE_specifics_t asn_SPC_NeighbourCell_Item_specs_1;
extern asn_TYPE_member_t asn_MBR_NeighbourCell_Item_1[2];
extern asn_per_constraints_t asn_PER_type_NeighbourCell_Item_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _NeighbourCell_Item_H_ */
#include "asn_internal.h"
