/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-RC-IEs"
 * 	found in "E2SM-RC-v06.00.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -fno-include-deps -findirect-choice -pdu=all -D ../../../lib/oran/e2sm/rc`
 */

#ifndef	_NeighbourCell_List_H_
#define	_NeighbourCell_List_H_


#include "asn_application.h"

/* Including external dependencies */
#include "asn_SEQUENCE_OF.h"
#include "constr_SEQUENCE_OF.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct NeighbourCell_Item;

/* NeighbourCell-List */
typedef struct NeighbourCell_List {
	A_SEQUENCE_OF(struct NeighbourCell_Item) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NeighbourCell_List_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NeighbourCell_List;
extern asn_SET_OF_specifics_t asn_SPC_NeighbourCell_List_specs_1;
extern asn_TYPE_member_t asn_MBR_NeighbourCell_List_1[1];
extern asn_per_constraints_t asn_PER_type_NeighbourCell_List_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _NeighbourCell_List_H_ */
#include "asn_internal.h"
