/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-RC-IEs"
 * 	found in "E2SM-RC-v06.00.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -fno-include-deps -findirect-choice -pdu=all -D ../../../lib/oran/e2sm/rc`
 */

#ifndef	_Ric_PolicyConditionID_H_
#define	_Ric_PolicyConditionID_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Ric-PolicyConditionID */
typedef long	 Ric_PolicyConditionID_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_Ric_PolicyConditionID_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_Ric_PolicyConditionID;
asn_struct_free_f Ric_PolicyConditionID_free;
asn_struct_print_f Ric_PolicyConditionID_print;
asn_constr_check_f Ric_PolicyConditionID_constraint;
ber_type_decoder_f Ric_PolicyConditionID_decode_ber;
der_type_encoder_f Ric_PolicyConditionID_encode_der;
xer_type_decoder_f Ric_PolicyConditionID_decode_xer;
xer_type_encoder_f Ric_PolicyConditionID_encode_xer;
jer_type_encoder_f Ric_PolicyConditionID_encode_jer;
oer_type_decoder_f Ric_PolicyConditionID_decode_oer;
oer_type_encoder_f Ric_PolicyConditionID_encode_oer;
per_type_decoder_f Ric_PolicyConditionID_decode_uper;
per_type_encoder_f Ric_PolicyConditionID_encode_uper;
per_type_decoder_f Ric_PolicyConditionID_decode_aper;
per_type_encoder_f Ric_PolicyConditionID_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _Ric_PolicyConditionID_H_ */
#include "asn_internal.h"
