/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-RC-IEs"
 * 	found in "E2SM-RC-v06.00.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -fno-include-deps -findirect-choice -pdu=all -D ../../../lib/oran/e2sm/rc`
 */

#ifndef	_UEQuery_H_
#define	_UEQuery_H_


#include "asn_application.h"

/* Including external dependencies */
#include "PartialUEID.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct RANParameter_Testing;

/* UEQuery */
typedef struct UEQuery {
	PartialUEID_t	 partialUEID;
	struct RANParameter_Testing	*ranParameterTesting;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} UEQuery_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UEQuery;
extern asn_SEQUENCE_specifics_t asn_SPC_UEQuery_specs_1;
extern asn_TYPE_member_t asn_MBR_UEQuery_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _UEQuery_H_ */
#include "asn_internal.h"
