/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-KPM-IEs"
 * 	found in "E2SM-KPM-v06.00.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -fno-include-deps -findirect-choice -pdu=all -D kpm`
 */

#ifndef	_JobID_H_
#define	_JobID_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* JobID */
typedef long	 JobID_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_JobID_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_JobID;
asn_struct_free_f JobID_free;
asn_struct_print_f JobID_print;
asn_constr_check_f JobID_constraint;
ber_type_decoder_f JobID_decode_ber;
der_type_encoder_f JobID_encode_der;
xer_type_decoder_f JobID_decode_xer;
xer_type_encoder_f JobID_encode_xer;
jer_type_encoder_f JobID_encode_jer;
oer_type_decoder_f JobID_decode_oer;
oer_type_encoder_f JobID_encode_oer;
per_type_decoder_f JobID_decode_uper;
per_type_encoder_f JobID_encode_uper;
per_type_decoder_f JobID_decode_aper;
per_type_encoder_f JobID_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _JobID_H_ */
#include "asn_internal.h"
