/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-KPM-IEs"
 * 	found in "E2SM-KPM-v06.00.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -fno-include-deps -findirect-choice -pdu=all -D kpm`
 */

#ifndef	_MultiReportActionDefinitionItem_H_
#define	_MultiReportActionDefinitionItem_H_


#include "asn_application.h"

/* Including external dependencies */
#include "JobID.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct E2SM_KPM_ActionDefinition;
struct CGI;
struct UEID;
struct MatchingUEidPerSubList;

/* MultiReportActionDefinitionItem */
typedef struct MultiReportActionDefinitionItem {
	JobID_t	 jobID;
	struct E2SM_KPM_ActionDefinition	*jobActionDefinition;	/* OPTIONAL */
	struct CGI	*jobCellGlobalID;	/* OPTIONAL */
	struct UEID	*jobUEID;	/* OPTIONAL */
	struct MatchingUEidPerSubList	*jobMatchingUEidList;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MultiReportActionDefinitionItem_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MultiReportActionDefinitionItem;
extern asn_SEQUENCE_specifics_t asn_SPC_MultiReportActionDefinitionItem_specs_1;
extern asn_TYPE_member_t asn_MBR_MultiReportActionDefinitionItem_1[5];

#ifdef __cplusplus
}
#endif

#endif	/* _MultiReportActionDefinitionItem_H_ */
#include "asn_internal.h"
