/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-KPM-IEs"
 * 	found in "E2SM-KPM-v06.00.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -fno-include-deps -findirect-choice -pdu=all -D kpm`
 */

#ifndef	_RIC_FundamentalLevelReportStyle_Item_H_
#define	_RIC_FundamentalLevelReportStyle_Item_H_


#include "asn_application.h"

/* Including external dependencies */
#include "RIC-Style-Type.h"
#include "NativeEnumerated.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum RIC_FundamentalLevelReportStyle_Item__jobSpecificActionDefinitionSupport {
	RIC_FundamentalLevelReportStyle_Item__jobSpecificActionDefinitionSupport_true	= 0
	/*
	 * Enumeration is extensible
	 */
} e_RIC_FundamentalLevelReportStyle_Item__jobSpecificActionDefinitionSupport;
typedef enum RIC_FundamentalLevelReportStyle_Item__jobSpecificCellGlobalIDSupport {
	RIC_FundamentalLevelReportStyle_Item__jobSpecificCellGlobalIDSupport_true	= 0
	/*
	 * Enumeration is extensible
	 */
} e_RIC_FundamentalLevelReportStyle_Item__jobSpecificCellGlobalIDSupport;
typedef enum RIC_FundamentalLevelReportStyle_Item__jobSpecificUEIDSupport {
	RIC_FundamentalLevelReportStyle_Item__jobSpecificUEIDSupport_true	= 0
	/*
	 * Enumeration is extensible
	 */
} e_RIC_FundamentalLevelReportStyle_Item__jobSpecificUEIDSupport;
typedef enum RIC_FundamentalLevelReportStyle_Item__jobSpecificMatchingUEidListSupport {
	RIC_FundamentalLevelReportStyle_Item__jobSpecificMatchingUEidListSupport_true	= 0
	/*
	 * Enumeration is extensible
	 */
} e_RIC_FundamentalLevelReportStyle_Item__jobSpecificMatchingUEidListSupport;

/* RIC-FundamentalLevelReportStyle-Item */
typedef struct RIC_FundamentalLevelReportStyle_Item {
	RIC_Style_Type_t	 ric_ReportStyle_Type;
	long	*jobSpecificActionDefinitionSupport;	/* OPTIONAL */
	long	*jobSpecificCellGlobalIDSupport;	/* OPTIONAL */
	long	*jobSpecificUEIDSupport;	/* OPTIONAL */
	long	*jobSpecificMatchingUEidListSupport;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RIC_FundamentalLevelReportStyle_Item_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_jobSpecificActionDefinitionSupport_3;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_jobSpecificCellGlobalIDSupport_6;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_jobSpecificUEIDSupport_9;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_jobSpecificMatchingUEidListSupport_12;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_RIC_FundamentalLevelReportStyle_Item;
extern asn_SEQUENCE_specifics_t asn_SPC_RIC_FundamentalLevelReportStyle_Item_specs_1;
extern asn_TYPE_member_t asn_MBR_RIC_FundamentalLevelReportStyle_Item_1[5];

#ifdef __cplusplus
}
#endif

#endif	/* _RIC_FundamentalLevelReportStyle_Item_H_ */
#include "asn_internal.h"
