/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-KPM-IEs"
 * 	found in "e2sm_kpm_v06_00.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -fno-include-deps -findirect-choice -pdu=all -D ../../../lib/oran/e2sm/kpm`
 */

#include "E2SM-KPM-IndicationMessage-Format255.h"

#include "MultiReportIndicationMessageList.h"
asn_TYPE_member_t asn_MBR_E2SM_KPM_IndicationMessage_Format255_1[] = {
	{ ATF_POINTER, 0, offsetof(struct E2SM_KPM_IndicationMessage_Format255, multiReportIndicationMessageList),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MultiReportIndicationMessageList,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"multiReportIndicationMessageList"
		},
};
static const ber_tlv_tag_t asn_DEF_E2SM_KPM_IndicationMessage_Format255_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_E2SM_KPM_IndicationMessage_Format255_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 } /* multiReportIndicationMessageList */
};
asn_SEQUENCE_specifics_t asn_SPC_E2SM_KPM_IndicationMessage_Format255_specs_1 = {
	sizeof(struct E2SM_KPM_IndicationMessage_Format255),
	offsetof(struct E2SM_KPM_IndicationMessage_Format255, _asn_ctx),
	asn_MAP_E2SM_KPM_IndicationMessage_Format255_tag2el_1,
	1,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_E2SM_KPM_IndicationMessage_Format255 = {
	"E2SM-KPM-IndicationMessage-Format255",
	"E2SM-KPM-IndicationMessage-Format255",
	&asn_OP_SEQUENCE,
	asn_DEF_E2SM_KPM_IndicationMessage_Format255_tags_1,
	sizeof(asn_DEF_E2SM_KPM_IndicationMessage_Format255_tags_1)
		/sizeof(asn_DEF_E2SM_KPM_IndicationMessage_Format255_tags_1[0]), /* 1 */
	asn_DEF_E2SM_KPM_IndicationMessage_Format255_tags_1,	/* Same as above */
	sizeof(asn_DEF_E2SM_KPM_IndicationMessage_Format255_tags_1)
		/sizeof(asn_DEF_E2SM_KPM_IndicationMessage_Format255_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_E2SM_KPM_IndicationMessage_Format255_1,
	1,	/* Elements count */
	&asn_SPC_E2SM_KPM_IndicationMessage_Format255_specs_1	/* Additional specs */
};

