/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-KPM-IEs"
 * 	found in "e2sm_kpm_v06_00.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -fno-include-deps -findirect-choice -pdu=all -D ../../../lib/oran/e2sm/kpm`
 */

#ifndef	_MeasValueTestCond_Expression_H_
#define	_MeasValueTestCond_Expression_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum MeasValueTestCond_Expression {
	MeasValueTestCond_Expression_equal	= 0,
	MeasValueTestCond_Expression_greaterthan	= 1,
	MeasValueTestCond_Expression_lessthan	= 2,
	MeasValueTestCond_Expression_contains	= 3,
	MeasValueTestCond_Expression_present	= 4
	/*
	 * Enumeration is extensible
	 */
} e_MeasValueTestCond_Expression;

/* MeasValueTestCond-Expression */
typedef long	 MeasValueTestCond_Expression_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_MeasValueTestCond_Expression_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_MeasValueTestCond_Expression;
extern const asn_INTEGER_specifics_t asn_SPC_MeasValueTestCond_Expression_specs_1;
asn_struct_free_f MeasValueTestCond_Expression_free;
asn_struct_print_f MeasValueTestCond_Expression_print;
asn_constr_check_f MeasValueTestCond_Expression_constraint;
ber_type_decoder_f MeasValueTestCond_Expression_decode_ber;
der_type_encoder_f MeasValueTestCond_Expression_encode_der;
xer_type_decoder_f MeasValueTestCond_Expression_decode_xer;
xer_type_encoder_f MeasValueTestCond_Expression_encode_xer;
jer_type_encoder_f MeasValueTestCond_Expression_encode_jer;
oer_type_decoder_f MeasValueTestCond_Expression_decode_oer;
oer_type_encoder_f MeasValueTestCond_Expression_encode_oer;
per_type_decoder_f MeasValueTestCond_Expression_decode_uper;
per_type_encoder_f MeasValueTestCond_Expression_encode_uper;
per_type_decoder_f MeasValueTestCond_Expression_decode_aper;
per_type_encoder_f MeasValueTestCond_Expression_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _MeasValueTestCond_Expression_H_ */
#include "asn_internal.h"
