/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-KPM-IEs"
 * 	found in "e2sm_kpm_v06_00.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -fno-include-deps -findirect-choice -pdu=all -D ../../../lib/oran/e2sm/kpm`
 */

#ifndef	_MultiReportApproach_H_
#define	_MultiReportApproach_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum MultiReportApproach {
	MultiReportApproach_single	= 0,
	MultiReportApproach_multiple	= 1
	/*
	 * Enumeration is extensible
	 */
} e_MultiReportApproach;

/* MultiReportApproach */
typedef long	 MultiReportApproach_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_MultiReportApproach_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_MultiReportApproach;
extern const asn_INTEGER_specifics_t asn_SPC_MultiReportApproach_specs_1;
asn_struct_free_f MultiReportApproach_free;
asn_struct_print_f MultiReportApproach_print;
asn_constr_check_f MultiReportApproach_constraint;
ber_type_decoder_f MultiReportApproach_decode_ber;
der_type_encoder_f MultiReportApproach_encode_der;
xer_type_decoder_f MultiReportApproach_decode_xer;
xer_type_encoder_f MultiReportApproach_encode_xer;
jer_type_encoder_f MultiReportApproach_encode_jer;
oer_type_decoder_f MultiReportApproach_decode_oer;
oer_type_encoder_f MultiReportApproach_encode_oer;
per_type_decoder_f MultiReportApproach_decode_uper;
per_type_encoder_f MultiReportApproach_encode_uper;
per_type_decoder_f MultiReportApproach_decode_aper;
per_type_encoder_f MultiReportApproach_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _MultiReportApproach_H_ */
#include "asn_internal.h"
