/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-KPM-IEs"
 * 	found in "e2sm_kpm_v06_00.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -fno-include-deps -findirect-choice -pdu=all -D ../../../lib/oran/e2sm/kpm`
 */

#ifndef	_MultiReportIndicationMessageList_H_
#define	_MultiReportIndicationMessageList_H_


#include "asn_application.h"

/* Including external dependencies */
#include "asn_SEQUENCE_OF.h"
#include "constr_SEQUENCE_OF.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct MultiReportIndicationMessageItem;

/* MultiReportIndicationMessageList */
typedef struct MultiReportIndicationMessageList {
	A_SEQUENCE_OF(struct MultiReportIndicationMessageItem) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MultiReportIndicationMessageList_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MultiReportIndicationMessageList;
extern asn_SET_OF_specifics_t asn_SPC_MultiReportIndicationMessageList_specs_1;
extern asn_TYPE_member_t asn_MBR_MultiReportIndicationMessageList_1[1];
extern asn_per_constraints_t asn_PER_type_MultiReportIndicationMessageList_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _MultiReportIndicationMessageList_H_ */
#include "asn_internal.h"
