/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-KPM-IEs"
 * 	found in "e2sm_kpm_v06_00.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -fno-include-deps -findirect-choice -pdu=all -D ../../../lib/oran/e2sm/kpm`
 */

#ifndef	_MultiReportActionDefinitionList_H_
#define	_MultiReportActionDefinitionList_H_


#include "asn_application.h"

/* Including external dependencies */
#include "asn_SEQUENCE_OF.h"
#include "constr_SEQUENCE_OF.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct MultiReportActionDefinitionItem;

/* MultiReportActionDefinitionList */
typedef struct MultiReportActionDefinitionList {
	A_SEQUENCE_OF(struct MultiReportActionDefinitionItem) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MultiReportActionDefinitionList_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MultiReportActionDefinitionList;
extern asn_SET_OF_specifics_t asn_SPC_MultiReportActionDefinitionList_specs_1;
extern asn_TYPE_member_t asn_MBR_MultiReportActionDefinitionList_1[1];
extern asn_per_constraints_t asn_PER_type_MultiReportActionDefinitionList_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _MultiReportActionDefinitionList_H_ */
#include "asn_internal.h"
