/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 */

struct asn_TYPE_descriptor_s;	/* Forward declaration */

extern struct asn_TYPE_descriptor_s asn_DEF_Beam_ID;
extern struct asn_TYPE_descriptor_s asn_DEF_Cell_RNTI;
extern struct asn_TYPE_descriptor_s asn_DEF_CGI;
extern struct asn_TYPE_descriptor_s asn_DEF_CoreCPID;
extern struct asn_TYPE_descriptor_s asn_DEF_InterfaceIdentifier;
extern struct asn_TYPE_descriptor_s asn_DEF_InterfaceID_NG;
extern struct asn_TYPE_descriptor_s asn_DEF_InterfaceID_Xn;
extern struct asn_TYPE_descriptor_s asn_DEF_InterfaceID_F1;
extern struct asn_TYPE_descriptor_s asn_DEF_InterfaceID_E1;
extern struct asn_TYPE_descriptor_s asn_DEF_InterfaceID_S1;
extern struct asn_TYPE_descriptor_s asn_DEF_InterfaceID_X2;
extern struct asn_TYPE_descriptor_s asn_DEF_InterfaceID_W1;
extern struct asn_TYPE_descriptor_s asn_DEF_Interface_MessageID;
extern struct asn_TYPE_descriptor_s asn_DEF_InterfaceType;
extern struct asn_TYPE_descriptor_s asn_DEF_GroupID;
extern struct asn_TYPE_descriptor_s asn_DEF_PartialUEID;
extern struct asn_TYPE_descriptor_s asn_DEF_QoSID;
extern struct asn_TYPE_descriptor_s asn_DEF_RANfunction_Name;
extern struct asn_TYPE_descriptor_s asn_DEF_RIC_Format_Type;
extern struct asn_TYPE_descriptor_s asn_DEF_RIC_Style_Type;
extern struct asn_TYPE_descriptor_s asn_DEF_RIC_Style_Name;
extern struct asn_TYPE_descriptor_s asn_DEF_RRC_MessageID;
extern struct asn_TYPE_descriptor_s asn_DEF_RRCclass_LTE;
extern struct asn_TYPE_descriptor_s asn_DEF_RRCclass_NR;
extern struct asn_TYPE_descriptor_s asn_DEF_ServingCell_ARFCN;
extern struct asn_TYPE_descriptor_s asn_DEF_ServingCell_PCI;
extern struct asn_TYPE_descriptor_s asn_DEF_UEID;
extern struct asn_TYPE_descriptor_s asn_DEF_UEID_GNB;
extern struct asn_TYPE_descriptor_s asn_DEF_UEID_GNB_CU_CP_E1AP_ID_List;
extern struct asn_TYPE_descriptor_s asn_DEF_UEID_GNB_CU_CP_E1AP_ID_Item;
extern struct asn_TYPE_descriptor_s asn_DEF_UEID_GNB_CU_F1AP_ID_List;
extern struct asn_TYPE_descriptor_s asn_DEF_UEID_GNB_CU_CP_F1AP_ID_Item;
extern struct asn_TYPE_descriptor_s asn_DEF_UEID_GNB_DU;
extern struct asn_TYPE_descriptor_s asn_DEF_UEID_GNB_CU_UP;
extern struct asn_TYPE_descriptor_s asn_DEF_UEID_NG_ENB;
extern struct asn_TYPE_descriptor_s asn_DEF_UEID_NG_ENB_DU;
extern struct asn_TYPE_descriptor_s asn_DEF_UEID_EN_GNB;
extern struct asn_TYPE_descriptor_s asn_DEF_UEID_ENB;
extern struct asn_TYPE_descriptor_s asn_DEF_ENB_ID;
extern struct asn_TYPE_descriptor_s asn_DEF_GlobalENB_ID;
extern struct asn_TYPE_descriptor_s asn_DEF_GUMMEI;
extern struct asn_TYPE_descriptor_s asn_DEF_MME_Group_ID;
extern struct asn_TYPE_descriptor_s asn_DEF_MME_Code;
extern struct asn_TYPE_descriptor_s asn_DEF_MME_UE_S1AP_ID;
extern struct asn_TYPE_descriptor_s asn_DEF_QCI;
extern struct asn_TYPE_descriptor_s asn_DEF_SubscriberProfileIDforRFP;
extern struct asn_TYPE_descriptor_s asn_DEF_EN_GNB_ID;
extern struct asn_TYPE_descriptor_s asn_DEF_ENB_UE_X2AP_ID;
extern struct asn_TYPE_descriptor_s asn_DEF_ENB_UE_X2AP_ID_Extension;
extern struct asn_TYPE_descriptor_s asn_DEF_E_UTRA_ARFCN;
extern struct asn_TYPE_descriptor_s asn_DEF_E_UTRA_PCI;
extern struct asn_TYPE_descriptor_s asn_DEF_E_UTRA_TAC;
extern struct asn_TYPE_descriptor_s asn_DEF_GlobalenGNB_ID;
extern struct asn_TYPE_descriptor_s asn_DEF_NGENB_CU_UE_W1AP_ID;
extern struct asn_TYPE_descriptor_s asn_DEF_NGENB_DU_ID;
extern struct asn_TYPE_descriptor_s asn_DEF_NR_SSB_Index;
extern struct asn_TYPE_descriptor_s asn_DEF_RNTI_Value;
extern struct asn_TYPE_descriptor_s asn_DEF_AMFPointer;
extern struct asn_TYPE_descriptor_s asn_DEF_AMFRegionID;
extern struct asn_TYPE_descriptor_s asn_DEF_AMFSetID;
extern struct asn_TYPE_descriptor_s asn_DEF_AMF_UE_NGAP_ID;
extern struct asn_TYPE_descriptor_s asn_DEF_EUTRACellIdentity;
extern struct asn_TYPE_descriptor_s asn_DEF_EUTRA_CGI;
extern struct asn_TYPE_descriptor_s asn_DEF_FiveQI;
extern struct asn_TYPE_descriptor_s asn_DEF_GlobalGNB_ID;
extern struct asn_TYPE_descriptor_s asn_DEF_GlobalNgENB_ID;
extern struct asn_TYPE_descriptor_s asn_DEF_GNB_ID;
extern struct asn_TYPE_descriptor_s asn_DEF_GUAMI;
extern struct asn_TYPE_descriptor_s asn_DEF_IndexToRFSP;
extern struct asn_TYPE_descriptor_s asn_DEF_NgENB_ID;
extern struct asn_TYPE_descriptor_s asn_DEF_NRCellIdentity;
extern struct asn_TYPE_descriptor_s asn_DEF_NR_CGI;
extern struct asn_TYPE_descriptor_s asn_DEF_PLMNIdentity;
extern struct asn_TYPE_descriptor_s asn_DEF_QosFlowIdentifier;
extern struct asn_TYPE_descriptor_s asn_DEF_SD;
extern struct asn_TYPE_descriptor_s asn_DEF_S_NSSAI;
extern struct asn_TYPE_descriptor_s asn_DEF_SST;
extern struct asn_TYPE_descriptor_s asn_DEF_NG_RANnodeUEXnAPID;
extern struct asn_TYPE_descriptor_s asn_DEF_GlobalNGRANNodeID;
extern struct asn_TYPE_descriptor_s asn_DEF_GNB_CU_CP_UE_E1AP_ID;
extern struct asn_TYPE_descriptor_s asn_DEF_GNB_CU_UP_ID;
extern struct asn_TYPE_descriptor_s asn_DEF_FiveGS_TAC;
extern struct asn_TYPE_descriptor_s asn_DEF_FreqBandNrItem;
extern struct asn_TYPE_descriptor_s asn_DEF_GNB_CU_UE_F1AP_ID;
extern struct asn_TYPE_descriptor_s asn_DEF_GNB_DU_ID;
extern struct asn_TYPE_descriptor_s asn_DEF_NR_PCI;
extern struct asn_TYPE_descriptor_s asn_DEF_NR_ARFCN;
extern struct asn_TYPE_descriptor_s asn_DEF_NRFrequencyBand_List;
extern struct asn_TYPE_descriptor_s asn_DEF_NRFrequencyBandItem;
extern struct asn_TYPE_descriptor_s asn_DEF_NRFrequencyInfo;
extern struct asn_TYPE_descriptor_s asn_DEF_NRFrequencyShift7p5khz;
extern struct asn_TYPE_descriptor_s asn_DEF_RANUEID;
extern struct asn_TYPE_descriptor_s asn_DEF_SupportedSULBandList;
extern struct asn_TYPE_descriptor_s asn_DEF_SupportedSULFreqBandItem;
extern struct asn_TYPE_descriptor_s asn_DEF_TimeStamp;
extern struct asn_TYPE_descriptor_s asn_DEF_BinIndex;
extern struct asn_TYPE_descriptor_s asn_DEF_BinRangeValue;
extern struct asn_TYPE_descriptor_s asn_DEF_JobID;
extern struct asn_TYPE_descriptor_s asn_DEF_GranularityPeriod;
extern struct asn_TYPE_descriptor_s asn_DEF_LogicalOR;
extern struct asn_TYPE_descriptor_s asn_DEF_MeasurementType;
extern struct asn_TYPE_descriptor_s asn_DEF_MeasurementTypeName;
extern struct asn_TYPE_descriptor_s asn_DEF_MeasurementTypeID;
extern struct asn_TYPE_descriptor_s asn_DEF_MeasurementLabel;
extern struct asn_TYPE_descriptor_s asn_DEF_TestCondInfo;
extern struct asn_TYPE_descriptor_s asn_DEF_TestCond_Type;
extern struct asn_TYPE_descriptor_s asn_DEF_TestCond_Expression;
extern struct asn_TYPE_descriptor_s asn_DEF_TestCond_Value;
extern struct asn_TYPE_descriptor_s asn_DEF_MultiReportApproach;
extern struct asn_TYPE_descriptor_s asn_DEF_BinRangeDefinition;
extern struct asn_TYPE_descriptor_s asn_DEF_BinRangeList;
extern struct asn_TYPE_descriptor_s asn_DEF_BinRangeItem;
extern struct asn_TYPE_descriptor_s asn_DEF_DistMeasurementBinRangeList;
extern struct asn_TYPE_descriptor_s asn_DEF_DistMeasurementBinRangeItem;
extern struct asn_TYPE_descriptor_s asn_DEF_MeasurementInfoList;
extern struct asn_TYPE_descriptor_s asn_DEF_MeasurementInfoItem;
extern struct asn_TYPE_descriptor_s asn_DEF_LabelInfoList;
extern struct asn_TYPE_descriptor_s asn_DEF_LabelInfoItem;
extern struct asn_TYPE_descriptor_s asn_DEF_MatchCondReportList;
extern struct asn_TYPE_descriptor_s asn_DEF_MatchCondReportItem;
extern struct asn_TYPE_descriptor_s asn_DEF_MeasValueReportCond;
extern struct asn_TYPE_descriptor_s asn_DEF_MeasValueTestCond_Expression;
extern struct asn_TYPE_descriptor_s asn_DEF_MeasurementData;
extern struct asn_TYPE_descriptor_s asn_DEF_MeasurementDataItem;
extern struct asn_TYPE_descriptor_s asn_DEF_MeasurementRecord;
extern struct asn_TYPE_descriptor_s asn_DEF_MeasurementRecordItem;
extern struct asn_TYPE_descriptor_s asn_DEF_MeasurementInfo_Action_List;
extern struct asn_TYPE_descriptor_s asn_DEF_MeasurementInfo_Action_Item;
extern struct asn_TYPE_descriptor_s asn_DEF_MeasurementCondList;
extern struct asn_TYPE_descriptor_s asn_DEF_MeasurementCondItem;
extern struct asn_TYPE_descriptor_s asn_DEF_MeasurementCondUEidList;
extern struct asn_TYPE_descriptor_s asn_DEF_MeasurementCondUEidItem;
extern struct asn_TYPE_descriptor_s asn_DEF_MatchingCondList;
extern struct asn_TYPE_descriptor_s asn_DEF_MatchingCondItem;
extern struct asn_TYPE_descriptor_s asn_DEF_MatchingCondItem_Choice;
extern struct asn_TYPE_descriptor_s asn_DEF_MatchingUEidList;
extern struct asn_TYPE_descriptor_s asn_DEF_MatchingUEidItem;
extern struct asn_TYPE_descriptor_s asn_DEF_MatchingUEidPerGP;
extern struct asn_TYPE_descriptor_s asn_DEF_MatchingUEidPerGP_Item;
extern struct asn_TYPE_descriptor_s asn_DEF_MatchingUEidList_PerGP;
extern struct asn_TYPE_descriptor_s asn_DEF_MatchingUEidItem_PerGP;
extern struct asn_TYPE_descriptor_s asn_DEF_MatchingUeCondPerSubList;
extern struct asn_TYPE_descriptor_s asn_DEF_MatchingUeCondPerSubItem;
extern struct asn_TYPE_descriptor_s asn_DEF_MatchingUEidPerSubList;
extern struct asn_TYPE_descriptor_s asn_DEF_MatchingUEidPerSubItem;
extern struct asn_TYPE_descriptor_s asn_DEF_MultiReportActionDefinitionList;
extern struct asn_TYPE_descriptor_s asn_DEF_MultiReportActionDefinitionItem;
extern struct asn_TYPE_descriptor_s asn_DEF_MultiReportIndicationMessageList;
extern struct asn_TYPE_descriptor_s asn_DEF_MultiReportIndicationMessageItem;
extern struct asn_TYPE_descriptor_s asn_DEF_UEMeasurementReportList;
extern struct asn_TYPE_descriptor_s asn_DEF_UEMeasurementReportItem;
extern struct asn_TYPE_descriptor_s asn_DEF_E2SM_KPM_EventTriggerDefinition;
extern struct asn_TYPE_descriptor_s asn_DEF_E2SM_KPM_EventTriggerDefinition_Format1;
extern struct asn_TYPE_descriptor_s asn_DEF_E2SM_KPM_ActionDefinition;
extern struct asn_TYPE_descriptor_s asn_DEF_E2SM_KPM_ActionDefinition_Format1;
extern struct asn_TYPE_descriptor_s asn_DEF_E2SM_KPM_ActionDefinition_Format2;
extern struct asn_TYPE_descriptor_s asn_DEF_E2SM_KPM_ActionDefinition_Format3;
extern struct asn_TYPE_descriptor_s asn_DEF_E2SM_KPM_ActionDefinition_Format4;
extern struct asn_TYPE_descriptor_s asn_DEF_E2SM_KPM_ActionDefinition_Format5;
extern struct asn_TYPE_descriptor_s asn_DEF_E2SM_KPM_ActionDefinition_Format255;
extern struct asn_TYPE_descriptor_s asn_DEF_E2SM_KPM_IndicationHeader;
extern struct asn_TYPE_descriptor_s asn_DEF_E2SM_KPM_IndicationHeader_Format1;
extern struct asn_TYPE_descriptor_s asn_DEF_E2SM_KPM_IndicationMessage;
extern struct asn_TYPE_descriptor_s asn_DEF_E2SM_KPM_IndicationMessage_Format1;
extern struct asn_TYPE_descriptor_s asn_DEF_E2SM_KPM_IndicationMessage_Format2;
extern struct asn_TYPE_descriptor_s asn_DEF_E2SM_KPM_IndicationMessage_Format3;
extern struct asn_TYPE_descriptor_s asn_DEF_E2SM_KPM_IndicationMessage_Format255;
extern struct asn_TYPE_descriptor_s asn_DEF_E2SM_KPM_RANfunction_Description;
extern struct asn_TYPE_descriptor_s asn_DEF_RIC_EventTriggerStyle_Item;
extern struct asn_TYPE_descriptor_s asn_DEF_RIC_ReportStyle_Item;
extern struct asn_TYPE_descriptor_s asn_DEF_RIC_IntegratedReportStyle_Item;
extern struct asn_TYPE_descriptor_s asn_DEF_RIC_FundamentalLevelReportStyle_Item;
extern struct asn_TYPE_descriptor_s asn_DEF_EXTERNAL;


struct asn_TYPE_descriptor_s *asn_pdu_collection[] = {
	/* From module E2SM-COMMON-IEs in e2sm_v07_00.asn */
	&asn_DEF_Beam_ID,	
	&asn_DEF_Cell_RNTI,	
	&asn_DEF_CGI,	
	&asn_DEF_CoreCPID,	
	&asn_DEF_InterfaceIdentifier,	
	&asn_DEF_InterfaceID_NG,	
	&asn_DEF_InterfaceID_Xn,	
	&asn_DEF_InterfaceID_F1,	
	&asn_DEF_InterfaceID_E1,	
	&asn_DEF_InterfaceID_S1,	
	&asn_DEF_InterfaceID_X2,	
	&asn_DEF_InterfaceID_W1,	
	&asn_DEF_Interface_MessageID,	
	&asn_DEF_InterfaceType,	
	&asn_DEF_GroupID,	
	&asn_DEF_PartialUEID,	
	&asn_DEF_QoSID,	
	&asn_DEF_RANfunction_Name,	
	&asn_DEF_RIC_Format_Type,	
	&asn_DEF_RIC_Style_Type,	
	&asn_DEF_RIC_Style_Name,	
	&asn_DEF_RRC_MessageID,	
	&asn_DEF_RRCclass_LTE,	
	&asn_DEF_RRCclass_NR,	
	&asn_DEF_ServingCell_ARFCN,	
	&asn_DEF_ServingCell_PCI,	
	&asn_DEF_UEID,	
	&asn_DEF_UEID_GNB,	
	&asn_DEF_UEID_GNB_CU_CP_E1AP_ID_List,	
	&asn_DEF_UEID_GNB_CU_CP_E1AP_ID_Item,	
	&asn_DEF_UEID_GNB_CU_F1AP_ID_List,	
	&asn_DEF_UEID_GNB_CU_CP_F1AP_ID_Item,	
	&asn_DEF_UEID_GNB_DU,	
	&asn_DEF_UEID_GNB_CU_UP,	
	&asn_DEF_UEID_NG_ENB,	
	&asn_DEF_UEID_NG_ENB_DU,	
	&asn_DEF_UEID_EN_GNB,	
	&asn_DEF_UEID_ENB,	
	&asn_DEF_ENB_ID,	
	&asn_DEF_GlobalENB_ID,	
	&asn_DEF_GUMMEI,	
	&asn_DEF_MME_Group_ID,	
	&asn_DEF_MME_Code,	
	&asn_DEF_MME_UE_S1AP_ID,	
	&asn_DEF_QCI,	
	&asn_DEF_SubscriberProfileIDforRFP,	
	&asn_DEF_EN_GNB_ID,	
	&asn_DEF_ENB_UE_X2AP_ID,	
	&asn_DEF_ENB_UE_X2AP_ID_Extension,	
	&asn_DEF_E_UTRA_ARFCN,	
	&asn_DEF_E_UTRA_PCI,	
	&asn_DEF_E_UTRA_TAC,	
	&asn_DEF_GlobalenGNB_ID,	
	&asn_DEF_NGENB_CU_UE_W1AP_ID,	
	&asn_DEF_NGENB_DU_ID,	
	&asn_DEF_NR_SSB_Index,	
	&asn_DEF_RNTI_Value,	
	&asn_DEF_AMFPointer,	
	&asn_DEF_AMFRegionID,	
	&asn_DEF_AMFSetID,	
	&asn_DEF_AMF_UE_NGAP_ID,	
	&asn_DEF_EUTRACellIdentity,	
	&asn_DEF_EUTRA_CGI,	
	&asn_DEF_FiveQI,	
	&asn_DEF_GlobalGNB_ID,	
	&asn_DEF_GlobalNgENB_ID,	
	&asn_DEF_GNB_ID,	
	&asn_DEF_GUAMI,	
	&asn_DEF_IndexToRFSP,	
	&asn_DEF_NgENB_ID,	
	&asn_DEF_NRCellIdentity,	
	&asn_DEF_NR_CGI,	
	&asn_DEF_PLMNIdentity,	
	&asn_DEF_QosFlowIdentifier,	
	&asn_DEF_SD,	
	&asn_DEF_S_NSSAI,	
	&asn_DEF_SST,	
	&asn_DEF_NG_RANnodeUEXnAPID,	
	&asn_DEF_GlobalNGRANNodeID,	
	&asn_DEF_GNB_CU_CP_UE_E1AP_ID,	
	&asn_DEF_GNB_CU_UP_ID,	
	&asn_DEF_FiveGS_TAC,	
	&asn_DEF_FreqBandNrItem,	
	&asn_DEF_GNB_CU_UE_F1AP_ID,	
	&asn_DEF_GNB_DU_ID,	
	&asn_DEF_NR_PCI,	
	&asn_DEF_NR_ARFCN,	
	&asn_DEF_NRFrequencyBand_List,	
	&asn_DEF_NRFrequencyBandItem,	
	&asn_DEF_NRFrequencyInfo,	
	&asn_DEF_NRFrequencyShift7p5khz,	
	&asn_DEF_RANUEID,	
	&asn_DEF_SupportedSULBandList,	
	&asn_DEF_SupportedSULFreqBandItem,	
	/* From module E2SM-KPM-IEs in e2sm_kpm_v06_00.asn */
	&asn_DEF_TimeStamp,	
	&asn_DEF_BinIndex,	
	&asn_DEF_BinRangeValue,	
	&asn_DEF_JobID,	
	&asn_DEF_GranularityPeriod,	
	&asn_DEF_LogicalOR,	
	&asn_DEF_MeasurementType,	
	&asn_DEF_MeasurementTypeName,	
	&asn_DEF_MeasurementTypeID,	
	&asn_DEF_MeasurementLabel,	
	&asn_DEF_TestCondInfo,	
	&asn_DEF_TestCond_Type,	
	&asn_DEF_TestCond_Expression,	
	&asn_DEF_TestCond_Value,	
	&asn_DEF_MultiReportApproach,	
	&asn_DEF_BinRangeDefinition,	
	&asn_DEF_BinRangeList,	
	&asn_DEF_BinRangeItem,	
	&asn_DEF_DistMeasurementBinRangeList,	
	&asn_DEF_DistMeasurementBinRangeItem,	
	&asn_DEF_MeasurementInfoList,	
	&asn_DEF_MeasurementInfoItem,	
	&asn_DEF_LabelInfoList,	
	&asn_DEF_LabelInfoItem,	
	&asn_DEF_MatchCondReportList,	
	&asn_DEF_MatchCondReportItem,	
	&asn_DEF_MeasValueReportCond,	
	&asn_DEF_MeasValueTestCond_Expression,	
	&asn_DEF_MeasurementData,	
	&asn_DEF_MeasurementDataItem,	
	&asn_DEF_MeasurementRecord,	
	&asn_DEF_MeasurementRecordItem,	
	&asn_DEF_MeasurementInfo_Action_List,	
	&asn_DEF_MeasurementInfo_Action_Item,	
	&asn_DEF_MeasurementCondList,	
	&asn_DEF_MeasurementCondItem,	
	&asn_DEF_MeasurementCondUEidList,	
	&asn_DEF_MeasurementCondUEidItem,	
	&asn_DEF_MatchingCondList,	
	&asn_DEF_MatchingCondItem,	
	&asn_DEF_MatchingCondItem_Choice,	
	&asn_DEF_MatchingUEidList,	
	&asn_DEF_MatchingUEidItem,	
	&asn_DEF_MatchingUEidPerGP,	
	&asn_DEF_MatchingUEidPerGP_Item,	
	&asn_DEF_MatchingUEidList_PerGP,	
	&asn_DEF_MatchingUEidItem_PerGP,	
	&asn_DEF_MatchingUeCondPerSubList,	
	&asn_DEF_MatchingUeCondPerSubItem,	
	&asn_DEF_MatchingUEidPerSubList,	
	&asn_DEF_MatchingUEidPerSubItem,	
	&asn_DEF_MultiReportActionDefinitionList,	
	&asn_DEF_MultiReportActionDefinitionItem,	
	&asn_DEF_MultiReportIndicationMessageList,	
	&asn_DEF_MultiReportIndicationMessageItem,	
	&asn_DEF_UEMeasurementReportList,	
	&asn_DEF_UEMeasurementReportItem,	
	&asn_DEF_E2SM_KPM_EventTriggerDefinition,	
	&asn_DEF_E2SM_KPM_EventTriggerDefinition_Format1,	
	&asn_DEF_E2SM_KPM_ActionDefinition,	
	&asn_DEF_E2SM_KPM_ActionDefinition_Format1,	
	&asn_DEF_E2SM_KPM_ActionDefinition_Format2,	
	&asn_DEF_E2SM_KPM_ActionDefinition_Format3,	
	&asn_DEF_E2SM_KPM_ActionDefinition_Format4,	
	&asn_DEF_E2SM_KPM_ActionDefinition_Format5,	
	&asn_DEF_E2SM_KPM_ActionDefinition_Format255,	
	&asn_DEF_E2SM_KPM_IndicationHeader,	
	&asn_DEF_E2SM_KPM_IndicationHeader_Format1,	
	&asn_DEF_E2SM_KPM_IndicationMessage,	
	&asn_DEF_E2SM_KPM_IndicationMessage_Format1,	
	&asn_DEF_E2SM_KPM_IndicationMessage_Format2,	
	&asn_DEF_E2SM_KPM_IndicationMessage_Format3,	
	&asn_DEF_E2SM_KPM_IndicationMessage_Format255,	
	&asn_DEF_E2SM_KPM_RANfunction_Description,	
	&asn_DEF_RIC_EventTriggerStyle_Item,	
	&asn_DEF_RIC_ReportStyle_Item,	
	&asn_DEF_RIC_IntegratedReportStyle_Item,	
	&asn_DEF_RIC_FundamentalLevelReportStyle_Item,	
	/* From module ASN1C-UsefulInformationObjectClasses in /usr/local/share/asn1c/standard-modules/ASN1C-UsefulInformationObjectClasses.asn1 */
	&asn_DEF_EXTERNAL,	
	0
};

