/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-KPM-IEs"
 * 	found in "e2sm_kpm_v06_00.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -fno-include-deps -findirect-choice -pdu=all -D ../../../lib/oran/e2sm/kpm`
 */

#include "RIC-FundamentalLevelReportStyle-Item.h"

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
#if !defined(ASN_DISABLE_OER_SUPPORT)
static asn_oer_constraints_t asn_OER_type_jobSpecificActionDefinitionSupport_constr_3 CC_NOTUSED = {
	{ 0, 0 },
	-1};
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
static asn_per_constraints_t asn_PER_type_jobSpecificActionDefinitionSupport_constr_3 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  0,  0,  0,  0 }	/* (0..0,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_OER_SUPPORT)
static asn_oer_constraints_t asn_OER_type_jobSpecificCellGlobalIDSupport_constr_6 CC_NOTUSED = {
	{ 0, 0 },
	-1};
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
static asn_per_constraints_t asn_PER_type_jobSpecificCellGlobalIDSupport_constr_6 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  0,  0,  0,  0 }	/* (0..0,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_OER_SUPPORT)
static asn_oer_constraints_t asn_OER_type_jobSpecificUEIDSupport_constr_9 CC_NOTUSED = {
	{ 0, 0 },
	-1};
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
static asn_per_constraints_t asn_PER_type_jobSpecificUEIDSupport_constr_9 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  0,  0,  0,  0 }	/* (0..0,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_OER_SUPPORT)
static asn_oer_constraints_t asn_OER_type_jobSpecificMatchingUEidListSupport_constr_12 CC_NOTUSED = {
	{ 0, 0 },
	-1};
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
static asn_per_constraints_t asn_PER_type_jobSpecificMatchingUEidListSupport_constr_12 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  0,  0,  0,  0 }	/* (0..0,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
static const asn_INTEGER_enum_map_t asn_MAP_jobSpecificActionDefinitionSupport_value2enum_3[] = {
	{ 0,	4,	"true" }
	/* This list is extensible */
};
static const unsigned int asn_MAP_jobSpecificActionDefinitionSupport_enum2value_3[] = {
	0	/* true(0) */
	/* This list is extensible */
};
static const asn_INTEGER_specifics_t asn_SPC_jobSpecificActionDefinitionSupport_specs_3 = {
	asn_MAP_jobSpecificActionDefinitionSupport_value2enum_3,	/* "tag" => N; sorted by tag */
	asn_MAP_jobSpecificActionDefinitionSupport_enum2value_3,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	2,	/* Extensions before this member */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_jobSpecificActionDefinitionSupport_tags_3[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_jobSpecificActionDefinitionSupport_3 = {
	"jobSpecificActionDefinitionSupport",
	"jobSpecificActionDefinitionSupport",
	&asn_OP_NativeEnumerated,
	asn_DEF_jobSpecificActionDefinitionSupport_tags_3,
	sizeof(asn_DEF_jobSpecificActionDefinitionSupport_tags_3)
		/sizeof(asn_DEF_jobSpecificActionDefinitionSupport_tags_3[0]) - 1, /* 1 */
	asn_DEF_jobSpecificActionDefinitionSupport_tags_3,	/* Same as above */
	sizeof(asn_DEF_jobSpecificActionDefinitionSupport_tags_3)
		/sizeof(asn_DEF_jobSpecificActionDefinitionSupport_tags_3[0]), /* 2 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		&asn_OER_type_jobSpecificActionDefinitionSupport_constr_3,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_jobSpecificActionDefinitionSupport_constr_3,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		NativeEnumerated_constraint
	},
	0, 0,	/* Defined elsewhere */
	&asn_SPC_jobSpecificActionDefinitionSupport_specs_3	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_jobSpecificCellGlobalIDSupport_value2enum_6[] = {
	{ 0,	4,	"true" }
	/* This list is extensible */
};
static const unsigned int asn_MAP_jobSpecificCellGlobalIDSupport_enum2value_6[] = {
	0	/* true(0) */
	/* This list is extensible */
};
static const asn_INTEGER_specifics_t asn_SPC_jobSpecificCellGlobalIDSupport_specs_6 = {
	asn_MAP_jobSpecificCellGlobalIDSupport_value2enum_6,	/* "tag" => N; sorted by tag */
	asn_MAP_jobSpecificCellGlobalIDSupport_enum2value_6,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	2,	/* Extensions before this member */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_jobSpecificCellGlobalIDSupport_tags_6[] = {
	(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_jobSpecificCellGlobalIDSupport_6 = {
	"jobSpecificCellGlobalIDSupport",
	"jobSpecificCellGlobalIDSupport",
	&asn_OP_NativeEnumerated,
	asn_DEF_jobSpecificCellGlobalIDSupport_tags_6,
	sizeof(asn_DEF_jobSpecificCellGlobalIDSupport_tags_6)
		/sizeof(asn_DEF_jobSpecificCellGlobalIDSupport_tags_6[0]) - 1, /* 1 */
	asn_DEF_jobSpecificCellGlobalIDSupport_tags_6,	/* Same as above */
	sizeof(asn_DEF_jobSpecificCellGlobalIDSupport_tags_6)
		/sizeof(asn_DEF_jobSpecificCellGlobalIDSupport_tags_6[0]), /* 2 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		&asn_OER_type_jobSpecificCellGlobalIDSupport_constr_6,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_jobSpecificCellGlobalIDSupport_constr_6,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		NativeEnumerated_constraint
	},
	0, 0,	/* Defined elsewhere */
	&asn_SPC_jobSpecificCellGlobalIDSupport_specs_6	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_jobSpecificUEIDSupport_value2enum_9[] = {
	{ 0,	4,	"true" }
	/* This list is extensible */
};
static const unsigned int asn_MAP_jobSpecificUEIDSupport_enum2value_9[] = {
	0	/* true(0) */
	/* This list is extensible */
};
static const asn_INTEGER_specifics_t asn_SPC_jobSpecificUEIDSupport_specs_9 = {
	asn_MAP_jobSpecificUEIDSupport_value2enum_9,	/* "tag" => N; sorted by tag */
	asn_MAP_jobSpecificUEIDSupport_enum2value_9,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	2,	/* Extensions before this member */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_jobSpecificUEIDSupport_tags_9[] = {
	(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_jobSpecificUEIDSupport_9 = {
	"jobSpecificUEIDSupport",
	"jobSpecificUEIDSupport",
	&asn_OP_NativeEnumerated,
	asn_DEF_jobSpecificUEIDSupport_tags_9,
	sizeof(asn_DEF_jobSpecificUEIDSupport_tags_9)
		/sizeof(asn_DEF_jobSpecificUEIDSupport_tags_9[0]) - 1, /* 1 */
	asn_DEF_jobSpecificUEIDSupport_tags_9,	/* Same as above */
	sizeof(asn_DEF_jobSpecificUEIDSupport_tags_9)
		/sizeof(asn_DEF_jobSpecificUEIDSupport_tags_9[0]), /* 2 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		&asn_OER_type_jobSpecificUEIDSupport_constr_9,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_jobSpecificUEIDSupport_constr_9,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		NativeEnumerated_constraint
	},
	0, 0,	/* Defined elsewhere */
	&asn_SPC_jobSpecificUEIDSupport_specs_9	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_jobSpecificMatchingUEidListSupport_value2enum_12[] = {
	{ 0,	4,	"true" }
	/* This list is extensible */
};
static const unsigned int asn_MAP_jobSpecificMatchingUEidListSupport_enum2value_12[] = {
	0	/* true(0) */
	/* This list is extensible */
};
static const asn_INTEGER_specifics_t asn_SPC_jobSpecificMatchingUEidListSupport_specs_12 = {
	asn_MAP_jobSpecificMatchingUEidListSupport_value2enum_12,	/* "tag" => N; sorted by tag */
	asn_MAP_jobSpecificMatchingUEidListSupport_enum2value_12,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	2,	/* Extensions before this member */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_jobSpecificMatchingUEidListSupport_tags_12[] = {
	(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_jobSpecificMatchingUEidListSupport_12 = {
	"jobSpecificMatchingUEidListSupport",
	"jobSpecificMatchingUEidListSupport",
	&asn_OP_NativeEnumerated,
	asn_DEF_jobSpecificMatchingUEidListSupport_tags_12,
	sizeof(asn_DEF_jobSpecificMatchingUEidListSupport_tags_12)
		/sizeof(asn_DEF_jobSpecificMatchingUEidListSupport_tags_12[0]) - 1, /* 1 */
	asn_DEF_jobSpecificMatchingUEidListSupport_tags_12,	/* Same as above */
	sizeof(asn_DEF_jobSpecificMatchingUEidListSupport_tags_12)
		/sizeof(asn_DEF_jobSpecificMatchingUEidListSupport_tags_12[0]), /* 2 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		&asn_OER_type_jobSpecificMatchingUEidListSupport_constr_12,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_jobSpecificMatchingUEidListSupport_constr_12,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		NativeEnumerated_constraint
	},
	0, 0,	/* Defined elsewhere */
	&asn_SPC_jobSpecificMatchingUEidListSupport_specs_12	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_RIC_FundamentalLevelReportStyle_Item_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RIC_FundamentalLevelReportStyle_Item, ric_ReportStyle_Type),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RIC_Style_Type,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"ric-ReportStyle-Type"
		},
	{ ATF_POINTER, 4, offsetof(struct RIC_FundamentalLevelReportStyle_Item, jobSpecificActionDefinitionSupport),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_jobSpecificActionDefinitionSupport_3,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"jobSpecificActionDefinitionSupport"
		},
	{ ATF_POINTER, 3, offsetof(struct RIC_FundamentalLevelReportStyle_Item, jobSpecificCellGlobalIDSupport),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_jobSpecificCellGlobalIDSupport_6,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"jobSpecificCellGlobalIDSupport"
		},
	{ ATF_POINTER, 2, offsetof(struct RIC_FundamentalLevelReportStyle_Item, jobSpecificUEIDSupport),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_jobSpecificUEIDSupport_9,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"jobSpecificUEIDSupport"
		},
	{ ATF_POINTER, 1, offsetof(struct RIC_FundamentalLevelReportStyle_Item, jobSpecificMatchingUEidListSupport),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_jobSpecificMatchingUEidListSupport_12,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"jobSpecificMatchingUEidListSupport"
		},
};
static const int asn_MAP_RIC_FundamentalLevelReportStyle_Item_oms_1[] = { 1, 2, 3, 4 };
static const ber_tlv_tag_t asn_DEF_RIC_FundamentalLevelReportStyle_Item_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_RIC_FundamentalLevelReportStyle_Item_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* ric-ReportStyle-Type */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* jobSpecificActionDefinitionSupport */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* jobSpecificCellGlobalIDSupport */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* jobSpecificUEIDSupport */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 } /* jobSpecificMatchingUEidListSupport */
};
asn_SEQUENCE_specifics_t asn_SPC_RIC_FundamentalLevelReportStyle_Item_specs_1 = {
	sizeof(struct RIC_FundamentalLevelReportStyle_Item),
	offsetof(struct RIC_FundamentalLevelReportStyle_Item, _asn_ctx),
	asn_MAP_RIC_FundamentalLevelReportStyle_Item_tag2el_1,
	5,	/* Count of tags in the map */
	asn_MAP_RIC_FundamentalLevelReportStyle_Item_oms_1,	/* Optional members */
	4, 0,	/* Root/Additions */
	5,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_RIC_FundamentalLevelReportStyle_Item = {
	"RIC-FundamentalLevelReportStyle-Item",
	"RIC-FundamentalLevelReportStyle-Item",
	&asn_OP_SEQUENCE,
	asn_DEF_RIC_FundamentalLevelReportStyle_Item_tags_1,
	sizeof(asn_DEF_RIC_FundamentalLevelReportStyle_Item_tags_1)
		/sizeof(asn_DEF_RIC_FundamentalLevelReportStyle_Item_tags_1[0]), /* 1 */
	asn_DEF_RIC_FundamentalLevelReportStyle_Item_tags_1,	/* Same as above */
	sizeof(asn_DEF_RIC_FundamentalLevelReportStyle_Item_tags_1)
		/sizeof(asn_DEF_RIC_FundamentalLevelReportStyle_Item_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_RIC_FundamentalLevelReportStyle_Item_1,
	5,	/* Elements count */
	&asn_SPC_RIC_FundamentalLevelReportStyle_Item_specs_1	/* Additional specs */
};

