/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-KPM-IEs"
 * 	found in "e2sm_kpm_v06_00.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -fno-include-deps -findirect-choice -pdu=all -D ../../../lib/oran/e2sm/kpm`
 */

#ifndef	_RIC_IntegratedReportStyle_Item_H_
#define	_RIC_IntegratedReportStyle_Item_H_


#include "asn_application.h"

/* Including external dependencies */
#include "RIC-Style-Type.h"
#include "RIC-Style-Name.h"
#include "RIC-Format-Type.h"
#include "NativeEnumerated.h"
#include "asn_SEQUENCE_OF.h"
#include "constr_SEQUENCE_OF.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum RIC_IntegratedReportStyle_Item__ric_SingleReportingApproachSupport {
	RIC_IntegratedReportStyle_Item__ric_SingleReportingApproachSupport_true	= 0
	/*
	 * Enumeration is extensible
	 */
} e_RIC_IntegratedReportStyle_Item__ric_SingleReportingApproachSupport;
typedef enum RIC_IntegratedReportStyle_Item__ric_MultipleReportingApproachSupport {
	RIC_IntegratedReportStyle_Item__ric_MultipleReportingApproachSupport_true	= 0
	/*
	 * Enumeration is extensible
	 */
} e_RIC_IntegratedReportStyle_Item__ric_MultipleReportingApproachSupport;
typedef enum RIC_IntegratedReportStyle_Item__ric_CommonActionDefinitionSupport {
	RIC_IntegratedReportStyle_Item__ric_CommonActionDefinitionSupport_true	= 0
	/*
	 * Enumeration is extensible
	 */
} e_RIC_IntegratedReportStyle_Item__ric_CommonActionDefinitionSupport;

/* Forward declarations */
struct RIC_FundamentalLevelReportStyle_Item;

/* RIC-IntegratedReportStyle-Item */
typedef struct RIC_IntegratedReportStyle_Item {
	RIC_Style_Type_t	 ric_ReportStyle_Type;
	RIC_Style_Name_t	 ric_ReportStyle_Name;
	RIC_Format_Type_t	 ric_ActionFormat_Type;
	RIC_Format_Type_t	 ric_IndicationHeaderFormat_Type;
	RIC_Format_Type_t	 ric_IndicationMessageFormat_Type;
	struct RIC_IntegratedReportStyle_Item__ric_FundamentalLevelReportStyle_List {
		A_SEQUENCE_OF(struct RIC_FundamentalLevelReportStyle_Item) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ric_FundamentalLevelReportStyle_List;
	long	*ric_SingleReportingApproachSupport;	/* OPTIONAL */
	long	*ric_MultipleReportingApproachSupport;	/* OPTIONAL */
	long	*ric_CommonActionDefinitionSupport;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RIC_IntegratedReportStyle_Item_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_ric_SingleReportingApproachSupport_9;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_ric_MultipleReportingApproachSupport_12;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_ric_CommonActionDefinitionSupport_15;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_RIC_IntegratedReportStyle_Item;
extern asn_SEQUENCE_specifics_t asn_SPC_RIC_IntegratedReportStyle_Item_specs_1;
extern asn_TYPE_member_t asn_MBR_RIC_IntegratedReportStyle_Item_1[9];

#ifdef __cplusplus
}
#endif

#endif	/* _RIC_IntegratedReportStyle_Item_H_ */
#include "asn_internal.h"
